import React, { useState } from 'react';
import { NormalizedRecord, CurrencyCode, ScenarioInputs } from '../types';
import { calculateCustomerAnalytics, calculateProductAnalytics } from '../utils/customerProductAnalytics';
import { calculateMetrics } from '../utils/metricsCalculator';
import { simulateScenario } from '../utils/forecastingEngine';
import { detectAnomalies } from '../utils/anomalyDetector';
import { formatCurrency } from '../utils/currencyFormatter';
import {
  Users,
  Package,
  Sliders,
  AlertTriangle,
  TrendingUp,
  Award,
  DollarSign,
  PieChart,
  Percent,
  CheckCircle2,
  HelpCircle,
  RefreshCw,
} from 'lucide-react';

interface AnalyticsViewProps {
  records: NormalizedRecord[];
  currency: CurrencyCode;
}

export const AnalyticsView: React.FC<AnalyticsViewProps> = ({ records, currency }) => {
  const customerStats = calculateCustomerAnalytics(records);
  const productStats = calculateProductAnalytics(records);
  const baseMetrics = calculateMetrics(records);
  const anomalies = detectAnomalies(records);

  const [scenarioInputs, setScenarioInputs] = useState<ScenarioInputs>({
    volumeChangePct: 10,
    priceChangePct: 5,
    expenseChangePct: 0,
  });

  const scenarioResult = simulateScenario(baseMetrics, scenarioInputs);

  const handleResetScenario = () => {
    setScenarioInputs({ volumeChangePct: 0, priceChangePct: 0, expenseChangePct: 0 });
  };

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 p-6 rounded-2xl border border-indigo-900/50 shadow-xl text-white">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-xs font-semibold text-indigo-400 uppercase tracking-widest mb-1">
              DataBeta Intelligence Suite
            </div>
            <h2 className="text-2xl font-bold tracking-tight">Customer, Product & Strategic Analytics</h2>
            <p className="text-xs text-slate-300 mt-1 max-w-2xl leading-relaxed">
              Explore customer concentration ratios, product unit margins, operational cost anomalies, and model future business growth with the real-time scenario simulator.
            </p>
          </div>

          <div className="flex items-center gap-2 bg-indigo-900/40 border border-indigo-700/50 px-3 py-2 rounded-xl text-xs text-indigo-200">
            <Award className="w-4 h-4 text-indigo-400" />
            <span>100% Client-Side Analytics</span>
          </div>
        </div>
      </div>

      {/* Grid: Customer Intelligence & Product Economics */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Customer Intelligence Card */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center font-bold shadow-sm">
                <Users className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-bold text-slate-900 text-base">Customer Concentration & LTV</h3>
                <p className="text-xs text-slate-500">Pareto 80/20 distribution & top client spend</p>
              </div>
            </div>
            <span className="text-xs bg-indigo-50 text-indigo-700 border border-indigo-200 font-semibold px-2.5 py-1 rounded-full">
              {customerStats.totalUniqueCustomers} Clients
            </span>
          </div>

          {/* Pareto 80/20 Stat Callout */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 grid grid-cols-2 gap-4">
            <div>
              <div className="text-xs text-slate-500 font-medium">Pareto 80/20 Concentration</div>
              <div className="text-xl font-bold text-indigo-600 mt-0.5">
                {customerStats.paretoRatioPct.toFixed(1)}%
              </div>
              <p className="text-[11px] text-slate-400 mt-0.5">Generated by top 20% of buyers</p>
            </div>

            <div>
              <div className="text-xs text-slate-500 font-medium">Top Client Share</div>
              <div className="text-xl font-bold text-slate-900 mt-0.5">
                {customerStats.topCustomerSharePct.toFixed(1)}%
              </div>
              <p className="text-[11px] text-slate-400 mt-0.5 truncate">
                {customerStats.topCustomerName || 'N/A'}
              </p>
            </div>
          </div>

          {/* Top Customer Leaderboard Table */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Top Accounts</h4>
            <div className="max-h-48 overflow-y-auto space-y-1.5 pr-1">
              {customerStats.topCustomersList.length > 0 ? (
                customerStats.topCustomersList.map((c, idx) => (
                  <div key={c.name} className="p-2.5 rounded-lg bg-slate-50/60 border border-slate-100 flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2 truncate">
                      <span className="w-5 h-5 rounded-full bg-indigo-100 text-indigo-700 font-bold text-[10px] flex items-center justify-center shrink-0">
                        #{idx + 1}
                      </span>
                      <span className="font-semibold text-slate-800 truncate">{c.name}</span>
                    </div>
                    <div className="text-right shrink-0">
                      <span className="font-bold text-slate-900">{formatCurrency(c.totalRevenue, currency)}</span>
                      <span className="text-[10px] text-slate-400 ml-1.5">({c.orderCount} orders)</span>
                    </div>
                  </div>
                ))
              ) : (
                <p className="text-xs text-slate-400 p-3 text-center">No customer identity columns mapped.</p>
              )}
            </div>
          </div>
        </div>

        {/* Product Margins & Unit Economics */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center font-bold shadow-sm">
                <Package className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-bold text-slate-900 text-base">Product Economics & Leaderboard</h3>
                <p className="text-xs text-slate-500">Unit prices & top product revenue drivers</p>
              </div>
            </div>
            <span className="text-xs bg-emerald-50 text-emerald-700 border border-emerald-200 font-semibold px-2.5 py-1 rounded-full">
              {productStats.totalProducts} Products
            </span>
          </div>

          {/* Top Product Callouts */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 grid grid-cols-2 gap-4">
            <div>
              <div className="text-xs text-slate-500 font-medium">Top Product by Sales</div>
              <div className="text-sm font-bold text-slate-900 truncate mt-1">
                {productStats.topProductByRevenue?.name || 'N/A'}
              </div>
              <p className="text-[11px] text-emerald-600 font-semibold mt-0.5">
                {formatCurrency(productStats.topProductByRevenue?.revenue || 0, currency)}
              </p>
            </div>

            <div>
              <div className="text-xs text-slate-500 font-medium">Highest Average Price</div>
              <div className="text-sm font-bold text-slate-900 truncate mt-1">
                {productStats.topProductByMargin?.name || 'N/A'}
              </div>
              <p className="text-[11px] text-indigo-600 font-semibold mt-0.5">
                {formatCurrency(productStats.topProductByMargin?.avgPrice || 0, currency)} / unit
              </p>
            </div>
          </div>

          {/* Product Leaderboard Table */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Product Performance</h4>
            <div className="max-h-48 overflow-y-auto space-y-1.5 pr-1">
              {productStats.productLeaderboard.length > 0 ? (
                productStats.productLeaderboard.map((p, idx) => (
                  <div key={p.name} className="p-2.5 rounded-lg bg-slate-50/60 border border-slate-100 flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2 truncate">
                      <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-700 font-bold text-[10px] flex items-center justify-center shrink-0">
                        #{idx + 1}
                      </span>
                      <span className="font-semibold text-slate-800 truncate">{p.name}</span>
                    </div>
                    <div className="text-right shrink-0">
                      <span className="font-bold text-slate-900">{formatCurrency(p.revenue, currency)}</span>
                      <span className="text-[10px] text-slate-400 ml-1.5">({p.quantity} units)</span>
                    </div>
                  </div>
                ))
              ) : (
                <p className="text-xs text-slate-400 p-3 text-center">No product columns mapped in dataset.</p>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Interactive What-If Growth Scenario Simulator */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-600 text-white flex items-center justify-center font-bold shadow-md shadow-indigo-600/30">
              <Sliders className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-slate-900 text-lg">Interactive "What-If" Growth Simulator</h3>
              <p className="text-xs text-slate-500">
                Adjust sliders to model how price increases, sales volume shifts, or cost cuts impact future profit margins.
              </p>
            </div>
          </div>

          <button
            onClick={handleResetScenario}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold rounded-lg transition-colors"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            <span>Reset Sliders</span>
          </button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Sliders Input Section */}
          <div className="lg:col-span-2 space-y-5 bg-slate-50/70 p-5 rounded-xl border border-slate-200">
            {/* Slider 1: Sales Volume */}
            <div>
              <div className="flex justify-between items-center text-xs font-semibold text-slate-800 mb-1.5">
                <span>Order Volume Adjustment:</span>
                <span className="text-indigo-600 font-mono font-bold text-sm">
                  {scenarioInputs.volumeChangePct > 0 ? '+' : ''}
                  {scenarioInputs.volumeChangePct}%
                </span>
              </div>
              <input
                type="range"
                min="-50"
                max="100"
                step="5"
                value={scenarioInputs.volumeChangePct}
                onChange={(e) =>
                  setScenarioInputs((prev) => ({ ...prev, volumeChangePct: Number(e.target.value) }))
                }
                className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-600"
              />
              <div className="flex justify-between text-[10px] text-slate-400 mt-1">
                <span>-50% (Downturn)</span>
                <span>0% (Baseline)</span>
                <span>+100% (Doubled Sales)</span>
              </div>
            </div>

            {/* Slider 2: Product Price */}
            <div>
              <div className="flex justify-between items-center text-xs font-semibold text-slate-800 mb-1.5">
                <span>Pricing Adjustment:</span>
                <span className="text-emerald-600 font-mono font-bold text-sm">
                  {scenarioInputs.priceChangePct > 0 ? '+' : ''}
                  {scenarioInputs.priceChangePct}%
                </span>
              </div>
              <input
                type="range"
                min="-30"
                max="50"
                step="1"
                value={scenarioInputs.priceChangePct}
                onChange={(e) =>
                  setScenarioInputs((prev) => ({ ...prev, priceChangePct: Number(e.target.value) }))
                }
                className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-emerald-600"
              />
              <div className="flex justify-between text-[10px] text-slate-400 mt-1">
                <span>-30% Discount</span>
                <span>0% (Current Price)</span>
                <span>+50% Premium</span>
              </div>
            </div>

            {/* Slider 3: Operational Expense */}
            <div>
              <div className="flex justify-between items-center text-xs font-semibold text-slate-800 mb-1.5">
                <span>Operational Expense Adjustment:</span>
                <span className="text-rose-600 font-mono font-bold text-sm">
                  {scenarioInputs.expenseChangePct > 0 ? '+' : ''}
                  {scenarioInputs.expenseChangePct}%
                </span>
              </div>
              <input
                type="range"
                min="-50"
                max="50"
                step="5"
                value={scenarioInputs.expenseChangePct}
                onChange={(e) =>
                  setScenarioInputs((prev) => ({ ...prev, expenseChangePct: Number(e.target.value) }))
                }
                className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-rose-600"
              />
              <div className="flex justify-between text-[10px] text-slate-400 mt-1">
                <span>-50% Cost Cut</span>
                <span>0% (Current Expenses)</span>
                <span>+50% Inflation</span>
              </div>
            </div>
          </div>

          {/* Live Scenario Projection Output Card */}
          <div className="bg-gradient-to-br from-slate-900 to-indigo-950 text-white p-5 rounded-xl shadow-lg border border-indigo-900 flex flex-col justify-between space-y-4">
            <div>
              <div className="text-xs font-semibold uppercase tracking-wider text-indigo-400 mb-1">
                Simulated Outcome
              </div>
              <h4 className="text-lg font-bold">Projected Net Impact</h4>
            </div>

            <div className="space-y-3 py-2 border-y border-indigo-900/80">
              <div>
                <div className="text-xs text-slate-300">Projected Revenue</div>
                <div className="text-xl font-bold text-white mt-0.5">
                  {formatCurrency(scenarioResult.projectedRevenue, currency)}
                </div>
              </div>

              <div>
                <div className="text-xs text-slate-300">Projected Profit</div>
                <div
                  className={`text-2xl font-black mt-0.5 ${
                    (scenarioResult.projectedProfit || 0) >= 0 ? 'text-emerald-400' : 'text-rose-400'
                  }`}
                >
                  {formatCurrency(scenarioResult.projectedProfit, currency)}
                </div>
              </div>

              <div className="flex items-center justify-between text-xs text-indigo-200 pt-1">
                <span>Projected Profit Margin:</span>
                <span className="font-bold text-white">
                  {scenarioResult.projectedMargin !== null ? `${scenarioResult.projectedMargin.toFixed(1)}%` : 'N/A'}
                </span>
              </div>
            </div>

            <div className="text-xs text-slate-300 bg-indigo-900/40 p-2.5 rounded-lg border border-indigo-700/40">
              <span className="font-semibold text-indigo-200">Net Delta: </span>
              <span className={scenarioResult.profitDelta >= 0 ? 'text-emerald-400 font-bold' : 'text-rose-400 font-bold'}>
                {scenarioResult.profitDelta >= 0 ? '+' : ''}
                {formatCurrency(scenarioResult.profitDelta, currency)}
              </span>{' '}
              vs current profit.
            </div>
          </div>
        </div>
      </div>

      {/* Operational Risk & Anomaly Detection Panel */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center font-bold shadow-sm">
            <AlertTriangle className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900 text-lg">Operational Risk & Anomaly Alerts</h3>
            <p className="text-xs text-slate-500">Automated evaluation of cost surges and financial risks</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {anomalies.length > 0 ? (
            anomalies.map((alert) => (
              <div
                key={alert.id}
                className={`p-4 rounded-xl border text-xs space-y-1 transition-all ${
                  alert.severity === 'high'
                    ? 'bg-rose-50/70 border-rose-200 text-rose-900'
                    : 'bg-amber-50/70 border-amber-200 text-amber-900'
                }`}
              >
                <div className="flex items-center justify-between font-bold text-sm">
                  <span>{alert.title}</span>
                  <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-white/80 border border-slate-200">
                    {alert.metric}
                  </span>
                </div>
                <p className="leading-relaxed opacity-90">{alert.description}</p>
              </div>
            ))
          ) : (
            <div className="col-span-2 p-6 rounded-xl bg-emerald-50/50 border border-emerald-200 text-emerald-900 flex items-center gap-3 text-xs">
              <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
              <div>
                <span className="font-bold text-slate-900">Zero Critical Anomalies Detected: </span>
                Your expenses, margins, and customer concentration ratios are operating within normal baseline parameters.
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
