import React, { useState, useEffect, useMemo } from 'react';
import { NormalizedRecord, CRMContact } from '../types';
import { CheckCircle2, Circle, Plus, ArrowUpRight, Calendar, Trash2 } from 'lucide-react';

interface PlannerTask {
  id: string;
  text: string;
  dueDate: string;
  completed: boolean;
  isAutoGenerated?: boolean;
}

interface BusinessPlannerCardProps {
  records: NormalizedRecord[];
  crmDeals: CRMContact[];
  onNavigateTab: (tab: 'overview' | 'transactions' | 'customers' | 'pipeline' | 'insights') => void;
}

const STORAGE_KEY = 'databeta_planner_tasks';

export const BusinessPlannerCard: React.FC<BusinessPlannerCardProps> = ({
  records,
  crmDeals,
  onNavigateTab,
}) => {
  // Generate smart operational recommendations from real data
  const defaultTasks = useMemo<PlannerTask[]>(() => {
    const list: PlannerTask[] = [];

    if (records.length === 0) {
      list.push({
        id: 'auto-1',
        text: 'Import your initial business CSV dataset',
        dueDate: 'Today',
        completed: false,
        isAutoGenerated: true,
      });
    } else {
      list.push({
        id: 'auto-2',
        text: `Audit ${records.length} imported transaction records`,
        dueDate: 'Today',
        completed: true,
        isAutoGenerated: true,
      });
    }

    if (crmDeals.length > 0) {
      const openCount = crmDeals.filter((d) => d.stage !== 'closed_won' && d.stage !== 'closed_lost').length;
      if (openCount > 0) {
        list.push({
          id: 'auto-3',
          text: `Follow up on ${openCount} active pipeline CRM deals`,
          dueDate: 'This Week',
          completed: false,
          isAutoGenerated: true,
        });
      }
    } else {
      list.push({
        id: 'auto-4',
        text: 'Add your first customer deal to the CRM pipeline',
        dueDate: 'This Week',
        completed: false,
        isAutoGenerated: true,
      });
    }

    list.push({
      id: 'auto-5',
      text: 'Export monthly financial P&L executive report',
      dueDate: 'Month End',
      completed: false,
      isAutoGenerated: true,
    });

    return list;
  }, [records, crmDeals]);

  const [tasks, setTasks] = useState<PlannerTask[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        return JSON.parse(saved);
      }
    } catch {}
    return defaultTasks;
  });

  const [newTaskText, setNewTaskText] = useState('');
  const [isAdding, setIsAdding] = useState(false);

  // Sync to local storage
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks));
    } catch {}
  }, [tasks]);

  const toggleTask = (id: string) => {
    setTasks((prev) =>
      prev.map((t) => (t.id === id ? { ...t, completed: !t.completed } : t))
    );
  };

  const handleAddTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskText.trim()) return;

    const newTask: PlannerTask = {
      id: `custom-${Date.now()}`,
      text: newTaskText.trim(),
      dueDate: 'Today',
      completed: false,
    };

    setTasks((prev) => [newTask, ...prev]);
    setNewTaskText('');
    setIsAdding(false);
  };

  const deleteTask = (id: string) => {
    setTasks((prev) => prev.filter((t) => t.id !== id));
  };

  return (
    <div className="bg-white dark:bg-zinc-950 p-6 rounded-3xl border border-slate-200/80 dark:border-zinc-800/80 shadow-xs flex flex-col justify-between space-y-4 h-full min-h-[220px]">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 dark:text-zinc-500">
            Operational Planner
          </span>
          <span className="text-[10px] bg-rose-50 dark:bg-rose-950/40 text-rose-600 dark:text-rose-400 font-bold px-2 py-0.5 rounded-full border border-rose-200 dark:border-rose-900/60">
            {tasks.filter((t) => t.completed).length}/{tasks.length} Completed
          </span>
        </div>

        <button
          onClick={() => setIsAdding(!isAdding)}
          className="text-xs font-bold text-rose-600 dark:text-rose-400 hover:underline flex items-center gap-1 active:scale-95 transition-all"
        >
          <Plus className="w-3.5 h-3.5" />
          <span>Add Task</span>
        </button>
      </div>

      {/* Add Task Form */}
      {isAdding && (
        <form onSubmit={handleAddTask} className="flex gap-2 animate-fadeIn">
          <input
            type="text"
            placeholder="Type new task item..."
            value={newTaskText}
            onChange={(e) => setNewTaskText(e.target.value)}
            className="flex-1 bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl px-3 py-1.5 text-xs text-slate-900 dark:text-white font-medium focus:outline-none focus:ring-2 focus:ring-rose-500"
            autoFocus
          />
          <button
            type="submit"
            className="px-4 py-1.5 bg-rose-600 text-white text-xs font-bold rounded-2xl shadow-xs hover:bg-rose-500 active:scale-95 transition-all"
          >
            Add
          </button>
        </form>
      )}

      {/* Tasks Checklist List */}
      <div className="space-y-2.5 overflow-y-auto max-h-48 scrollbar-none pr-1">
        {tasks.map((task) => (
          <div
            key={task.id}
            className={`p-2.5 rounded-2xl border transition-all flex items-center justify-between gap-3 group ${
              task.completed
                ? 'bg-slate-50/50 dark:bg-zinc-900/30 border-slate-200/50 dark:border-zinc-900 text-slate-400 dark:text-zinc-500'
                : 'bg-slate-50/80 dark:bg-zinc-900/60 border-slate-200/80 dark:border-zinc-800 text-slate-900 dark:text-zinc-100 hover:border-slate-300 dark:hover:border-zinc-700'
            }`}
          >
            <div
              onClick={() => toggleTask(task.id)}
              className="flex items-center gap-3 cursor-pointer flex-1 truncate"
            >
              <div className="shrink-0 transition-transform active:scale-90">
                {task.completed ? (
                  <CheckCircle2 className="w-4 h-4 text-rose-600 dark:text-rose-500" />
                ) : (
                  <Circle className="w-4 h-4 text-slate-400 dark:text-zinc-500 group-hover:text-rose-600" />
                )}
              </div>
              <span
                className={`text-xs font-semibold truncate ${
                  task.completed ? 'line-through opacity-75' : ''
                }`}
              >
                {task.text}
              </span>
            </div>

            <div className="flex items-center gap-2 shrink-0">
              <span className="text-[10px] font-mono text-slate-400 dark:text-zinc-500 bg-white dark:bg-zinc-950 px-2 py-0.5 rounded-full border border-slate-200/60 dark:border-zinc-800/60">
                {task.dueDate}
              </span>
              {!task.isAutoGenerated && (
                <button
                  onClick={() => deleteTask(task.id)}
                  className="opacity-0 group-hover:opacity-100 text-slate-400 hover:text-rose-600 transition-opacity p-1"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
