import React, { useState, useEffect, useMemo } from 'react';
import { NormalizedRecord, CRMContact, CurrencyCode } from '../types';
import { CheckCircle2, Circle, Plus, ArrowUpRight, Target, Trash2, AlertTriangle, Zap, DollarSign } from 'lucide-react';
import { detectAnomalies } from '../intelligence/anomalyEngine';

interface PlannerTask {
  id: string;
  text: string;
  dueDate: string;
  completed: boolean;
  isAutoGenerated?: boolean;
  icon?: React.ReactNode;
}

interface BusinessPlannerCardProps {
  records: NormalizedRecord[];
  crmDeals: CRMContact[];
  currency: CurrencyCode;
  onNavigateTab: (tab: 'overview' | 'transactions' | 'customers' | 'pipeline' | 'insights') => void;
}

const STORAGE_KEY = 'databeta_planner_tasks_v2';

export const BusinessPlannerCard: React.FC<BusinessPlannerCardProps> = ({
  records,
  crmDeals,
  currency,
  onNavigateTab,
}) => {
  // Generate smart operational recommendations from anomalies and CRM
  const defaultTasks = useMemo<PlannerTask[]>(() => {
    const list: PlannerTask[] = [];

    if (records.length === 0) {
      list.push({
        id: 'auto-1',
        text: 'Import your business CSV to generate insights',
        dueDate: 'Today',
        completed: false,
        isAutoGenerated: true,
        icon: <Zap className="w-3.5 h-3.5 text-amber-500" />
      });
      return list;
    }

    // 1. Pending AR / Pipeline Cash
    const openDeals = crmDeals.filter(d => d.stage === 'proposal' || d.stage === 'negotiation');
    if (openDeals.length > 0) {
       list.push({
          id: 'auto-pipeline',
          text: `Follow up on ${openDeals.length} high-probability pending invoices/deals`,
          dueDate: 'Today',
          completed: false,
          isAutoGenerated: true,
          icon: <DollarSign className="w-3.5 h-3.5 text-emerald-500" />
       });
    }

    // 2. Anomaly Driven Tasks
    const anomalies = detectAnomalies(records, currency);
    const criticalAnomalies = anomalies.filter(a => a.severity === 'high' || a.severity === 'medium');

    criticalAnomalies.slice(0, 2).forEach((anom, idx) => {
       list.push({
          id: `auto-anom-${idx}`,
          text: `Action Required: ${anom.title}`,
          dueDate: 'Today',
          completed: false,
          isAutoGenerated: true,
          icon: <AlertTriangle className="w-3.5 h-3.5 text-rose-500" />
       });
    });

    if (list.length < 3) {
       list.push({
          id: 'auto-review',
          text: 'Review Schedule C tax deductions for current period',
          dueDate: 'This Week',
          completed: false,
          isAutoGenerated: true,
          icon: <Target className="w-3.5 h-3.5 text-indigo-500" />
       });
    }

    return list;
  }, [records, crmDeals, currency]);

  const [tasks, setTasks] = useState<PlannerTask[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        return JSON.parse(saved);
      }
    } catch {}
    return defaultTasks;
  });

  // Re-sync default tasks if records change significantly (simplified for demo)
  useEffect(() => {
    if (tasks.length === 0 || defaultTasks.length > tasks.length) {
       // Merge logic could be complex, for this prototype we just append new auto ones if missing
       const existingIds = new Set(tasks.map(t => t.id));
       const newTasks = defaultTasks.filter(dt => !existingIds.has(dt.id));
       if (newTasks.length > 0) {
          setTasks(prev => [...newTasks, ...prev]);
       }
    }
  }, [defaultTasks]);

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks));
    } catch {}
  }, [tasks]);

  const toggleTask = (id: string) => {
    setTasks(tasks.map((t) => (t.id === id ? { ...t, completed: !t.completed } : t)));
  };

  const removeTask = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setTasks(tasks.filter((t) => t.id !== id));
  };

  const [newTaskText, setNewTaskText] = useState('');
  const [isAdding, setIsAdding] = useState(false);

  const handleAddTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskText.trim()) return;
    setTasks([
      {
        id: `manual-${Date.now()}`,
        text: newTaskText.trim(),
        dueDate: 'Upcoming',
        completed: false,
      },
      ...tasks,
    ]);
    setNewTaskText('');
    setIsAdding(false);
  };

  const uncompleted = tasks.filter((t) => !t.completed);
  const completed = tasks.filter((t) => t.completed);
  const displayTasks = [...uncompleted, ...completed].slice(0, 5); // Show max 5 in widget

  return (
    <div className="bg-white dark:bg-zinc-950 p-6 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs flex flex-col justify-between h-full min-h-[220px]">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <span className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 dark:text-zinc-500">
            Smart Action Center
          </span>
          {uncompleted.length > 0 && (
            <span className="px-1.5 py-0.5 rounded-full bg-rose-100 dark:bg-rose-950/40 text-[9px] font-bold text-rose-600 dark:text-rose-400">
              {uncompleted.length}
            </span>
          )}
        </div>
        <button
          onClick={() => setIsAdding(!isAdding)}
          className="w-6 h-6 rounded-full bg-slate-100 dark:bg-zinc-900 hover:bg-slate-200 dark:hover:bg-zinc-800 flex items-center justify-center transition-colors text-slate-500 dark:text-zinc-400 hover:text-slate-900 dark:hover:text-white"
        >
          <Plus className="w-3 h-3" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto pr-1 custom-scrollbar space-y-1.5 -mx-1 px-1">
        {isAdding && (
          <form onSubmit={handleAddTask} className="mb-2">
            <input
              type="text"
              autoFocus
              placeholder="What needs to be done?"
              value={newTaskText}
              onChange={(e) => setNewTaskText(e.target.value)}
              onBlur={() => {
                if (!newTaskText) setIsAdding(false);
              }}
              className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-lg px-3 py-2 text-xs text-slate-900 dark:text-white placeholder:text-slate-400 dark:placeholder:text-zinc-600 focus:outline-none focus:ring-2 focus:ring-rose-500/50"
            />
          </form>
        )}

        {displayTasks.map((task) => (
          <div
            key={task.id}
            onClick={() => toggleTask(task.id)}
            className={`group flex items-start gap-3 p-2 rounded-xl transition-all cursor-pointer ${
              task.completed
                ? 'opacity-50 hover:opacity-75'
                : 'hover:bg-slate-50 dark:hover:bg-zinc-900/50'
            }`}
          >
            <button className="shrink-0 mt-0.5 text-slate-400 dark:text-zinc-500 transition-colors group-hover:text-rose-500">
              {task.completed ? (
                <CheckCircle2 className="w-4 h-4 text-emerald-500" />
              ) : (
                <Circle className="w-4 h-4" />
              )}
            </button>
            <div className="flex-1 min-w-0">
              <p
                className={`text-xs font-medium truncate ${
                  task.completed
                    ? 'text-slate-400 dark:text-zinc-500 line-through'
                    : 'text-slate-700 dark:text-zinc-300'
                }`}
              >
                {task.text}
              </p>
              <div className="flex items-center gap-1.5 mt-0.5">
                {task.isAutoGenerated && !task.completed && task.icon}
                <span className="text-[9px] font-bold text-slate-400 dark:text-zinc-500 uppercase">
                  {task.dueDate}
                </span>
              </div>
            </div>
            <button
              onClick={(e) => removeTask(task.id, e)}
              className="opacity-0 group-hover:opacity-100 shrink-0 p-1 rounded-md text-slate-400 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-950/40 transition-all"
            >
              <Trash2 className="w-3.5 h-3.5" />
            </button>
          </div>
        ))}

        {displayTasks.length === 0 && !isAdding && (
          <div className="flex flex-col items-center justify-center h-full text-center py-6">
            <CheckCircle2 className="w-6 h-6 text-slate-300 dark:text-zinc-700 mb-2" />
            <p className="text-xs text-slate-500 dark:text-zinc-400 font-medium">All caught up!</p>
          </div>
        )}
      </div>

      <div className="pt-4 mt-2 border-t border-slate-100 dark:border-zinc-800/80">
        <button
          onClick={() => onNavigateTab('insights')}
          className="w-full text-center text-[10px] font-bold uppercase tracking-wider text-rose-600 dark:text-rose-500 hover:text-rose-700 dark:hover:text-rose-400 transition-colors"
        >
          View Full AI Insights
        </button>
      </div>
    </div>
  );
};
