import React, { useState, useEffect, useMemo } from 'react';
import { CRMContact, CRMStage, CurrencyCode, NormalizedRecord, CRMTask, CRMActivity, CRMCompany } from '../types';
import { formatCurrency } from '../utils/currencyFormatter';
import { calculatePipelineSummary, autoGenerateDealsFromRecords } from '../utils/crmEngine';
import { calculateCustomerAnalytics } from '../utils/customerProductAnalytics';
import { crmService } from '../services/crmService';
import { Customer360Drawer, CustomerDetail } from './Customer360Drawer';
import {
  Users,
  GitPullRequest,
  Plus,
  Search,
  Filter,
  Trash2,
  Mail,
  Phone,
  Calendar,
  CheckCircle2,
  Clock,
  ArrowRight,
  Zap,
  TrendingUp,
  Building,
  CheckSquare,
  Activity,
  Layers,
  ChevronRight,
  DollarSign,
  X,
  AlertTriangle,
  Award,
} from 'lucide-react';

interface CRMViewProps {
  contacts: CRMContact[];
  onContactsChange: (contacts: CRMContact[]) => void;
  currency: CurrencyCode;
  records: NormalizedRecord[];
  activeBusinessId?: string;
}

type CRMSubtab = 'pipeline' | 'contacts' | 'companies' | 'activities' | 'tasks';

const KANBAN_STAGES: { key: CRMStage; label: string; color: string; hexColor: string; probabilityPct: number }[] = [
  { key: 'lead', label: 'Lead', color: 'bg-zinc-800 text-zinc-300', hexColor: '#64748b', probabilityPct: 10 },
  { key: 'qualified', label: 'Qualified', color: 'bg-blue-950 text-blue-400 border-blue-900', hexColor: '#3b82f6', probabilityPct: 30 },
  { key: 'proposal', label: 'Proposal', color: 'bg-purple-950 text-purple-400 border-purple-900', hexColor: '#a855f7', probabilityPct: 60 },
  { key: 'negotiation', label: 'Negotiation', color: 'bg-amber-950 text-amber-400 border-amber-900', hexColor: '#f59e0b', probabilityPct: 80 },
  { key: 'closed_won', label: 'Won', color: 'bg-emerald-950 text-emerald-400 border-emerald-900', hexColor: '#10b981', probabilityPct: 100 },
  { key: 'closed_lost', label: 'Lost', color: 'bg-rose-950 text-rose-400 border-rose-900', hexColor: '#ef4444', probabilityPct: 0 },
];

export const CRMView: React.FC<CRMViewProps> = ({
  contacts,
  onContactsChange,
  currency,
  records,
  activeBusinessId,
}) => {
  const [subtab, setSubtab] = useState<CRMSubtab>('pipeline');
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedDrawerCustomer, setSelectedDrawerCustomer] = useState<CustomerDetail | null>(null);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  // Modals
  const [showAddDealModal, setShowAddDealModal] = useState(false);
  const [showAddTaskModal, setShowAddTaskModal] = useState(false);

  // Form State for Deal
  const [dealCompany, setDealCompany] = useState('');
  const [dealContactName, setDealContactName] = useState('');
  const [dealEmail, setDealEmail] = useState('');
  const [dealPhone, setDealPhone] = useState('');
  const [dealStage, setDealStage] = useState<CRMStage>('lead');
  const [dealValue, setDealValue] = useState<number | ''>(10000);
  const [dealTag, setDealTag] = useState('Enterprise');
  const [dealNotes, setDealNotes] = useState('');

  // Tasks State
  const [tasks, setTasks] = useState<CRMTask[]>([
    {
      id: 'task-1',
      title: 'Send formal SOW and payment schedule',
      dueDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
      priority: 'urgent',
      status: 'pending',
      contactName: 'Sarah Jenkins',
      dealTitle: 'Enterprise SLA Expansion',
      createdAt: new Date().toISOString().split('T')[0],
    },
    {
      id: 'task-2',
      title: 'Executive discovery call re: Q3 expansion',
      dueDate: new Date(Date.now() + 172800000).toISOString().split('T')[0],
      priority: 'high',
      status: 'pending',
      contactName: 'David Zhang',
      dealTitle: 'Platform Licensing',
      createdAt: new Date().toISOString().split('T')[0],
    },
    {
      id: 'task-3',
      title: 'Check in on procurement approval',
      dueDate: new Date(Date.now() - 86400000).toISOString().split('T')[0],
      priority: 'normal',
      status: 'completed',
      contactName: 'Marcus Miller',
      dealTitle: 'Consulting Retainer',
      createdAt: new Date().toISOString().split('T')[0],
    },
  ]);

  // Form State for Task
  const [taskTitle, setTaskTitle] = useState('');
  const [taskDueDate, setTaskDueDate] = useState(new Date().toISOString().split('T')[0]);
  const [taskPriority, setTaskPriority] = useState<'urgent' | 'high' | 'normal'>('high');
  const [taskContact, setTaskContact] = useState('');

  // Auto-populate pipeline if currently empty
  useEffect(() => {
    if (contacts.length === 0 && records.length > 0) {
      const generated = autoGenerateDealsFromRecords(records);
      onContactsChange(generated);
    }
  }, [records, contacts.length]);

  const pipelineSummary = useMemo(() => calculatePipelineSummary(contacts), [contacts]);

  // Weighted Expected Pipeline Value
  const weightedPipelineValue = useMemo(() => {
    let sum = 0;
    contacts.forEach((c) => {
      const stageConfig = KANBAN_STAGES.find((s) => s.key === c.stage);
      const prob = stageConfig ? stageConfig.probabilityPct / 100 : 0.2;
      sum += (c.dealValue || 0) * prob;
    });
    return sum;
  }, [contacts]);

  // Companies aggregated list
  const companiesList: CRMCompany[] = useMemo(() => {
    const map: Record<string, { totalSpent: number; openPipeline: number; deals: number; contacts: number }> = {};

    contacts.forEach((c) => {
      const comp = (c.company || c.name || 'Individual').trim();
      if (!map[comp]) {
        map[comp] = { totalSpent: 0, openPipeline: 0, deals: 0, contacts: 0 };
      }
      map[comp].deals += 1;
      map[comp].contacts += 1;
      if (c.stage === 'closed_won') {
        map[comp].totalSpent += c.dealValue || 0;
      } else if (c.stage !== 'closed_lost') {
        map[comp].openPipeline += c.dealValue || 0;
      }
    });

    records.forEach((r) => {
      if (r.customer) {
        const comp = r.customer.trim();
        if (map[comp]) {
          map[comp].totalSpent += r.revenue || 0;
        } else {
          map[comp] = { totalSpent: r.revenue || 0, openPipeline: 0, deals: 0, contacts: 1 };
        }
      }
    });

    return Object.entries(map).map(([name, data], idx) => ({
      id: `comp-${idx}`,
      name,
      domain: `${name.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`,
      industry: 'Software & Technology',
      tier: data.totalSpent >= 25000 ? 'Enterprise' : data.totalSpent >= 5000 ? 'Mid-Market' : 'SMB',
      contactsCount: Math.max(1, data.contacts),
      dealsCount: data.deals,
      openPipelineValue: data.openPipeline,
      lifetimeRevenue: data.totalSpent,
      createdAt: '2026-01-15',
    })).sort((a, b) => (b.lifetimeRevenue + b.openPipelineValue) - (a.lifetimeRevenue + a.openPipelineValue));
  }, [contacts, records]);

  // Advance deal to next stage
  const handleAdvanceStage = (contactId: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    const stageOrder: CRMStage[] = ['lead', 'qualified', 'proposal', 'negotiation', 'closed_won'];
    const updated = contacts.map((c) => {
      if (c.id !== contactId) return c;
      const currIdx = stageOrder.indexOf(c.stage);
      if (currIdx >= 0 && currIdx < stageOrder.length - 1) {
        const nextStage = stageOrder[currIdx + 1];
        if (activeBusinessId) {
          crmService.updateDealStage(activeBusinessId, c.id, nextStage);
        }
        return { ...c, stage: nextStage };
      }
      return c;
    });
    onContactsChange(updated);
  };

  // Move deal to specific stage
  const handleMoveStage = (contactId: string, targetStage: CRMStage) => {
    const updated = contacts.map((c) => {
      if (c.id !== contactId) return c;
      if (activeBusinessId) {
        crmService.updateDealStage(activeBusinessId, c.id, targetStage);
      }
      return { ...c, stage: targetStage };
    });
    onContactsChange(updated);
  };

  // Delete Deal
  const handleDeleteDeal = (contactId: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    if (window.confirm('Delete this deal from the pipeline?')) {
      const updated = contacts.filter((c) => c.id !== contactId);
      onContactsChange(updated);
      if (activeBusinessId) {
        crmService.deleteDeal(activeBusinessId, contactId);
      }
    }
  };

  // Handle Create Deal
  const handleCreateDeal = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!dealContactName.trim() && !dealCompany.trim()) return;

    const val = Number(dealValue) || 5000;
    const newDeal: CRMContact = {
      id: `deal-${Date.now()}`,
      name: dealContactName.trim() || dealCompany.trim(),
      company: dealCompany.trim() || dealContactName.trim(),
      email: dealEmail.trim() || 'contact@client.com',
      phone: dealPhone.trim() || '+1 (555) 019-2831',
      stage: dealStage,
      dealValue: val,
      tags: [dealTag],
      notes: dealNotes.trim() || 'Created via Sales Pipeline CRM',
      lastContactDate: 'Today',
      createdAt: new Date().toISOString().split('T')[0],
      totalSpent: val,
      orderCount: 1,
    };

    if (activeBusinessId) {
      await crmService.createDeal(activeBusinessId, {
        name: newDeal.name,
        company: newDeal.company,
        email: newDeal.email,
        phone: newDeal.phone,
        stage: newDeal.stage,
        dealValue: newDeal.dealValue,
        tags: newDeal.tags,
        notes: newDeal.notes,
      });
    }

    onContactsChange([newDeal, ...contacts]);
    setShowAddDealModal(false);
    setDealCompany('');
    setDealContactName('');
    setDealEmail('');
    setDealPhone('');
    setDealNotes('');
  };

  // Handle Create Task
  const handleCreateTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!taskTitle.trim()) return;

    const newTask: CRMTask = {
      id: `task-${Date.now()}`,
      title: taskTitle.trim(),
      dueDate: taskDueDate,
      priority: taskPriority,
      status: 'pending',
      contactName: taskContact.trim() || undefined,
      createdAt: new Date().toISOString().split('T')[0],
    };

    setTasks([newTask, ...tasks]);
    setShowAddTaskModal(false);
    setTaskTitle('');
    setTaskContact('');
  };

  // Toggle Task Status
  const handleToggleTask = (taskId: string) => {
    setTasks(tasks.map((t) => (t.id === taskId ? { ...t, status: t.status === 'pending' ? 'completed' : 'pending' } : t)));
  };

  // Open Customer 360 Drawer
  const handleOpen360 = (contactOrCompany: { name: string; totalSpent?: number; orderCount?: number }) => {
    const detail: CustomerDetail = {
      name: contactOrCompany.name,
      totalSpent: contactOrCompany.totalSpent || 0,
      orderCount: contactOrCompany.orderCount || 1,
      firstPurchase: '2026-01-10',
      lastPurchase: '2026-03-01',
    };
    setSelectedDrawerCustomer(detail);
    setIsDrawerOpen(true);
  };

  // Filtered lists
  const filteredDeals = useMemo(() => {
    return contacts.filter((c) => {
      const q = searchTerm.toLowerCase();
      return (
        c.name.toLowerCase().includes(q) ||
        c.company.toLowerCase().includes(q) ||
        c.email.toLowerCase().includes(q)
      );
    });
  }, [contacts, searchTerm]);

  return (
    <div className="space-y-6">
      {/* CRM Studio Top Header */}
      <div className="bg-white dark:bg-zinc-950 p-6 sm:p-7 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-extrabold uppercase tracking-widest text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-950/60 border border-rose-200 dark:border-rose-900/60 px-2.5 py-0.5 rounded-full">
              Connected Customer Operating System
            </span>
            <span className="text-xs text-slate-400 dark:text-zinc-500 font-mono">
              • {contacts.length} opportunities • {companiesList.length} accounts
            </span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white tracking-tight">
            Sales & Relationship CRM
          </h2>
          <p className="text-xs text-slate-500 dark:text-zinc-400 mt-1 max-w-xl">
            Unified pipeline management, account histories, customer 360 dossiers, and follow-up tasks.
          </p>
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          <button
            onClick={() => setShowAddTaskModal(true)}
            className="px-4 py-2.5 bg-slate-100 dark:bg-zinc-900 hover:bg-slate-200 dark:hover:bg-zinc-800 text-slate-800 dark:text-zinc-200 text-xs font-extrabold rounded-full transition-all flex items-center gap-2 border border-slate-200 dark:border-zinc-800 active:scale-[0.98]"
          >
            <CheckSquare className="w-3.5 h-3.5 text-rose-600" />
            <span>+ Task</span>
          </button>

          <button
            onClick={() => setShowAddDealModal(true)}
            className="px-5 py-2.5 bg-rose-600 hover:bg-rose-500 text-white text-xs font-extrabold rounded-full shadow-md shadow-rose-600/30 transition-all flex items-center gap-2 active:scale-[0.98]"
          >
            <Plus className="w-4 h-4" />
            <span>+ New Deal</span>
          </button>
        </div>
      </div>

      {/* 4 Pipeline Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white dark:bg-zinc-950 p-5 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs space-y-1 hover-card-subtle">
          <span className="text-[10px] font-bold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">Total Pipeline Value</span>
          <div className="text-2xl font-black text-slate-900 dark:text-white font-mono tabular-nums">
            {formatCurrency(pipelineSummary.totalPipelineValue, currency)}
          </div>
          <p className="text-[11px] text-slate-400 dark:text-zinc-500 font-mono">{pipelineSummary.totalDeals} open deals</p>
        </div>

        <div className="bg-white dark:bg-zinc-950 p-5 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs space-y-1 hover-card-subtle">
          <span className="text-[10px] font-bold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">Weighted Forecast</span>
          <div className="text-2xl font-black text-indigo-600 dark:text-indigo-400 font-mono tabular-nums">
            {formatCurrency(weightedPipelineValue, currency)}
          </div>
          <p className="text-[11px] text-slate-400 dark:text-zinc-500">Stage probability weighted</p>
        </div>

        <div className="bg-white dark:bg-zinc-950 p-5 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs space-y-1 hover-card-subtle">
          <span className="text-[10px] font-bold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">Win Rate</span>
          <div className="text-2xl font-black text-emerald-600 dark:text-emerald-400 font-mono tabular-nums">
            {pipelineSummary.winRatePct.toFixed(0)}%
          </div>
          <p className="text-[11px] text-slate-400 dark:text-zinc-500">Historical conversion pace</p>
        </div>

        <div className="bg-white dark:bg-zinc-950 p-5 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs space-y-1 hover-card-subtle">
          <span className="text-[10px] font-bold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">Avg Deal Size</span>
          <div className="text-2xl font-black text-slate-900 dark:text-white font-mono tabular-nums">
            {formatCurrency(pipelineSummary.avgDealSize, currency)}
          </div>
          <p className="text-[11px] text-slate-400 dark:text-zinc-500">Average contract value</p>
        </div>
      </div>

      {/* Subtab Navigation Bar */}
      <div className="bg-white dark:bg-zinc-950 p-2 rounded-2xl border border-slate-200/80 dark:border-zinc-800 shadow-xs flex items-center justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-1.5 overflow-x-auto">
          <button
            onClick={() => setSubtab('pipeline')}
            className={`px-4 py-2 rounded-xl text-xs font-extrabold transition-all ${
              subtab === 'pipeline'
                ? 'bg-rose-600 text-white shadow-xs'
                : 'text-slate-600 dark:text-zinc-400 hover:bg-slate-100 dark:hover:bg-zinc-900'
            }`}
          >
            <div className="flex items-center gap-2">
              <GitPullRequest className="w-3.5 h-3.5" />
              <span>Pipeline Kanban</span>
            </div>
          </button>

          <button
            onClick={() => setSubtab('contacts')}
            className={`px-4 py-2 rounded-xl text-xs font-extrabold transition-all ${
              subtab === 'contacts'
                ? 'bg-rose-600 text-white shadow-xs'
                : 'text-slate-600 dark:text-zinc-400 hover:bg-slate-100 dark:hover:bg-zinc-900'
            }`}
          >
            <div className="flex items-center gap-2">
              <Users className="w-3.5 h-3.5" />
              <span>Contacts & Leads ({contacts.length})</span>
            </div>
          </button>

          <button
            onClick={() => setSubtab('companies')}
            className={`px-4 py-2 rounded-xl text-xs font-extrabold transition-all ${
              subtab === 'companies'
                ? 'bg-rose-600 text-white shadow-xs'
                : 'text-slate-600 dark:text-zinc-400 hover:bg-slate-100 dark:hover:bg-zinc-900'
            }`}
          >
            <div className="flex items-center gap-2">
              <Building className="w-3.5 h-3.5" />
              <span>Companies ({companiesList.length})</span>
            </div>
          </button>

          <button
            onClick={() => setSubtab('tasks')}
            className={`px-4 py-2 rounded-xl text-xs font-extrabold transition-all ${
              subtab === 'tasks'
                ? 'bg-rose-600 text-white shadow-xs'
                : 'text-slate-600 dark:text-zinc-400 hover:bg-slate-100 dark:hover:bg-zinc-900'
            }`}
          >
            <div className="flex items-center gap-2">
              <CheckSquare className="w-3.5 h-3.5" />
              <span>Tasks & Follow-ups ({tasks.filter((t) => t.status === 'pending').length})</span>
            </div>
          </button>
        </div>

        {/* Universal Search Input */}
        <div className="relative w-full sm:w-64">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
          <input
            type="text"
            placeholder="Search CRM records..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl pl-9 pr-3 py-1.5 text-xs text-slate-900 dark:text-white placeholder-slate-400 dark:placeholder-zinc-500 focus:outline-none focus:ring-1 focus:ring-rose-500"
          />
        </div>
      </div>

      {/* Subtab 1: Pipeline Kanban */}
      {subtab === 'pipeline' && (
        <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-3 overflow-x-auto pb-4">
          {KANBAN_STAGES.map((stage) => {
            const stageDeals = filteredDeals.filter((d) => d.stage === stage.key);
            const totalStageValue = stageDeals.reduce((sum, d) => sum + (d.dealValue || 0), 0);

            return (
              <div
                key={stage.key}
                className="bg-slate-100/60 dark:bg-zinc-900/60 p-3 rounded-2xl border border-slate-200/80 dark:border-zinc-800 flex flex-col min-w-[200px] max-h-[75vh]"
              >
                {/* Column Header */}
                <div className="flex items-center justify-between pb-2 border-b border-slate-200 dark:border-zinc-800 mb-3">
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: stage.hexColor }} />
                    <span className="text-xs font-black text-slate-900 dark:text-white uppercase tracking-wider">{stage.label}</span>
                  </div>
                  <span className="text-[10px] font-mono font-extrabold text-slate-500 dark:text-zinc-400 bg-white dark:bg-zinc-800 px-2 py-0.5 rounded-full">
                    {stageDeals.length}
                  </span>
                </div>

                <div className="text-[11px] font-mono font-bold text-slate-500 dark:text-zinc-400 mb-3 px-1">
                  {formatCurrency(totalStageValue, currency)}
                </div>

                {/* Cards List */}
                <div className="flex-1 space-y-2 overflow-y-auto pr-1 custom-scrollbar">
                  {stageDeals.map((deal) => (
                    <div
                      key={deal.id}
                      onClick={() => handleOpen360(deal)}
                      className="bg-white dark:bg-zinc-950 p-3.5 rounded-xl border border-slate-200/80 dark:border-zinc-800 shadow-xs hover:border-rose-500/50 cursor-pointer transition-all space-y-2 group"
                    >
                      <div className="flex items-start justify-between gap-1">
                        <h4 className="font-extrabold text-xs text-slate-900 dark:text-white line-clamp-1">
                          {deal.company || deal.name}
                        </h4>
                        <button
                          onClick={(e) => handleDeleteDeal(deal.id, e)}
                          className="opacity-0 group-hover:opacity-100 p-1 text-slate-400 hover:text-rose-500 transition-opacity"
                        >
                          <Trash2 className="w-3 h-3" />
                        </button>
                      </div>

                      <div className="text-[11px] text-slate-500 dark:text-zinc-400 line-clamp-1">{deal.name}</div>

                      <div className="flex items-center justify-between pt-1 border-t border-slate-100 dark:border-zinc-900">
                        <span className="font-black text-xs text-slate-900 dark:text-white font-mono">
                          {formatCurrency(deal.dealValue, currency)}
                        </span>

                        {stage.key !== 'closed_won' && stage.key !== 'closed_lost' && (
                          <button
                            onClick={(e) => handleAdvanceStage(deal.id, e)}
                            title="Advance to next stage"
                            className="p-1 rounded-lg bg-slate-100 dark:bg-zinc-900 text-slate-600 dark:text-zinc-400 hover:bg-rose-600 hover:text-white transition-colors"
                          >
                            <ChevronRight className="w-3 h-3" />
                          </button>
                        )}
                      </div>
                    </div>
                  ))}

                  {stageDeals.length === 0 && (
                    <div className="p-4 text-center text-[10px] text-slate-400 dark:text-zinc-600 border border-dashed border-slate-200 dark:border-zinc-800 rounded-xl">
                      Empty stage
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Subtab 2: Contacts & Leads Directory */}
      {subtab === 'contacts' && (
        <div className="bg-white dark:bg-zinc-950 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="bg-slate-100 dark:bg-zinc-900 text-slate-600 dark:text-zinc-400 font-bold uppercase text-[10px] border-b border-slate-200 dark:border-zinc-800">
                  <th className="p-4">Contact / Lead</th>
                  <th className="p-4">Company</th>
                  <th className="p-4">Stage</th>
                  <th className="p-4">Email / Phone</th>
                  <th className="p-4 text-right">Deal Value</th>
                  <th className="p-4 text-center">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-zinc-900">
                {filteredDeals.map((contact) => (
                  <tr
                    key={contact.id}
                    onClick={() => handleOpen360(contact)}
                    className="hover:bg-slate-50 dark:hover:bg-zinc-900/50 cursor-pointer transition-colors"
                  >
                    <td className="p-4">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full bg-rose-50 dark:bg-rose-950/60 text-rose-600 font-bold flex items-center justify-center border border-rose-200 dark:border-rose-900/60 shrink-0">
                          {contact.name.charAt(0).toUpperCase()}
                        </div>
                        <div>
                          <div className="font-extrabold text-slate-900 dark:text-white">{contact.name}</div>
                          <div className="text-[10px] text-slate-400 dark:text-zinc-500">{contact.tags?.[0] || 'Enterprise'}</div>
                        </div>
                      </div>
                    </td>
                    <td className="p-4 font-bold text-slate-800 dark:text-zinc-200">{contact.company || '—'}</td>
                    <td className="p-4">
                      <span className="px-2.5 py-1 rounded-full text-[10px] font-extrabold uppercase bg-slate-100 dark:bg-zinc-900 text-slate-700 dark:text-zinc-300 border border-slate-200 dark:border-zinc-800">
                        {contact.stage.replace('_', ' ')}
                      </span>
                    </td>
                    <td className="p-4 text-slate-500 dark:text-zinc-400">
                      <div>{contact.email}</div>
                      <div className="text-[10px] font-mono">{contact.phone}</div>
                    </td>
                    <td className="p-4 text-right font-black text-slate-900 dark:text-white font-mono">
                      {formatCurrency(contact.dealValue, currency)}
                    </td>
                    <td className="p-4 text-center">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleOpen360(contact);
                        }}
                        className="p-1.5 text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 rounded-lg transition-colors"
                      >
                        <ChevronRight className="w-4 h-4" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Subtab 3: Companies Directory */}
      {subtab === 'companies' && (
        <div className="bg-white dark:bg-zinc-950 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="bg-slate-100 dark:bg-zinc-900 text-slate-600 dark:text-zinc-400 font-bold uppercase text-[10px] border-b border-slate-200 dark:border-zinc-800">
                  <th className="p-4">Company Account</th>
                  <th className="p-4">Tier / Industry</th>
                  <th className="p-4">Associated Contacts</th>
                  <th className="p-4 text-right">Open Pipeline</th>
                  <th className="p-4 text-right">Lifetime Revenue</th>
                  <th className="p-4 text-center">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-zinc-900">
                {companiesList.map((comp) => (
                  <tr
                    key={comp.id}
                    onClick={() => handleOpen360({ name: comp.name, totalSpent: comp.lifetimeRevenue })}
                    className="hover:bg-slate-50 dark:hover:bg-zinc-900/50 cursor-pointer transition-colors"
                  >
                    <td className="p-4">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-xl bg-slate-100 dark:bg-zinc-900 text-slate-700 dark:text-zinc-300 font-bold flex items-center justify-center border border-slate-200 dark:border-zinc-800 shrink-0">
                          <Building className="w-4 h-4" />
                        </div>
                        <div>
                          <div className="font-extrabold text-slate-900 dark:text-white">{comp.name}</div>
                          <div className="text-[10px] font-mono text-slate-400">{comp.domain}</div>
                        </div>
                      </div>
                    </td>
                    <td className="p-4">
                      <span className="px-2.5 py-0.5 rounded-full text-[10px] font-extrabold uppercase bg-rose-50 dark:bg-rose-950/60 text-rose-600 dark:text-rose-400 border border-rose-200 dark:border-rose-900/60">
                        {comp.tier}
                      </span>
                    </td>
                    <td className="p-4 font-mono text-slate-600 dark:text-zinc-400">{comp.contactsCount} contacts</td>
                    <td className="p-4 text-right font-bold text-indigo-600 dark:text-indigo-400 font-mono">
                      {formatCurrency(comp.openPipelineValue, currency)}
                    </td>
                    <td className="p-4 text-right font-black text-slate-900 dark:text-white font-mono">
                      {formatCurrency(comp.lifetimeRevenue, currency)}
                    </td>
                    <td className="p-4 text-center">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleOpen360({ name: comp.name, totalSpent: comp.lifetimeRevenue });
                        }}
                        className="p-1.5 text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 rounded-lg transition-colors"
                      >
                        <ChevronRight className="w-4 h-4" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Subtab 4: Tasks & Follow-ups */}
      {subtab === 'tasks' && (
        <div className="bg-white dark:bg-zinc-950 p-6 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="font-extrabold text-slate-900 dark:text-white text-base">Actionable Follow-up Tasks</h3>
            <button
              onClick={() => setShowAddTaskModal(true)}
              className="px-4 py-2 bg-rose-600 hover:bg-rose-500 text-white text-xs font-bold rounded-full shadow-xs transition-all flex items-center gap-1.5"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>Create Task</span>
            </button>
          </div>

          <div className="space-y-2">
            {tasks.map((task) => (
              <div
                key={task.id}
                onClick={() => handleToggleTask(task.id)}
                className={`p-4 rounded-2xl border transition-all cursor-pointer flex items-center justify-between ${
                  task.status === 'completed'
                    ? 'bg-slate-50/50 dark:bg-zinc-900/30 border-slate-200 dark:border-zinc-900 opacity-60'
                    : 'bg-white dark:bg-zinc-950 border-slate-200/80 dark:border-zinc-800 hover:border-rose-500/40 shadow-xs'
                }`}
              >
                <div className="flex items-center gap-3">
                  <div
                    className={`w-5 h-5 rounded-md border flex items-center justify-center ${
                      task.status === 'completed'
                        ? 'bg-emerald-600 border-emerald-600 text-white'
                        : 'border-slate-300 dark:border-zinc-700'
                    }`}
                  >
                    {task.status === 'completed' && <CheckCircle2 className="w-4 h-4" />}
                  </div>
                  <div>
                    <div className={`font-extrabold text-xs ${task.status === 'completed' ? 'line-through text-slate-400' : 'text-slate-900 dark:text-white'}`}>
                      {task.title}
                    </div>
                    <div className="text-[10px] text-slate-500 dark:text-zinc-400 mt-0.5">
                      {task.contactName && `Client: ${task.contactName} • `} Due: {task.dueDate}
                    </div>
                  </div>
                </div>

                <span
                  className={`text-[10px] font-extrabold uppercase px-2.5 py-0.5 rounded-full ${
                    task.priority === 'urgent'
                      ? 'bg-rose-50 text-rose-600 dark:bg-rose-950/60 dark:text-rose-400 border border-rose-200'
                      : task.priority === 'high'
                      ? 'bg-amber-50 text-amber-600 dark:bg-amber-950/60 dark:text-amber-400 border border-amber-200'
                      : 'bg-slate-100 text-slate-600 dark:bg-zinc-900 dark:text-zinc-400'
                  }`}
                >
                  {task.priority}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Customer 360 Slide-in Drawer */}
      {isDrawerOpen && selectedDrawerCustomer && (
        <Customer360Drawer
          customer={selectedDrawerCustomer}
          currency={currency}
          records={records}
          crmDeals={contacts}
          onClose={() => setIsDrawerOpen(false)}
        />
      )}

      {/* Add Deal Modal */}
      {showAddDealModal && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white dark:bg-zinc-950 rounded-3xl p-6 max-w-md w-full border border-slate-200 dark:border-zinc-800 shadow-2xl space-y-4 animate-fadeIn">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-zinc-900">
              <h3 className="font-black text-slate-900 dark:text-white text-lg">Create New Deal</h3>
              <button onClick={() => setShowAddDealModal(false)} className="p-1 rounded-full text-slate-400 hover:text-white">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleCreateDeal} className="space-y-3 text-xs">
              <div>
                <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Company / Account</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Stripe, Acme Corp"
                  value={dealCompany}
                  onChange={(e) => setDealCompany(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 text-slate-900 dark:text-white"
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Primary Contact</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Jane Doe"
                    value={dealContactName}
                    onChange={(e) => setDealContactName(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 text-slate-900 dark:text-white"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Deal Value ({currency})</label>
                  <input
                    type="number"
                    required
                    value={dealValue}
                    onChange={(e) => setDealValue(e.target.value === '' ? '' : Number(e.target.value))}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 font-mono font-bold text-slate-900 dark:text-white"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Email</label>
                  <input
                    type="email"
                    placeholder="contact@company.com"
                    value={dealEmail}
                    onChange={(e) => setDealEmail(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 text-slate-900 dark:text-white"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Initial Stage</label>
                  <select
                    value={dealStage}
                    onChange={(e) => setDealStage(e.target.value as CRMStage)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 text-slate-900 dark:text-white"
                  >
                    <option value="lead">Lead</option>
                    <option value="qualified">Qualified</option>
                    <option value="proposal">Proposal</option>
                    <option value="negotiation">Negotiation</option>
                    <option value="closed_won">Closed Won</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Notes / Context</label>
                <textarea
                  rows={2}
                  placeholder="Key background notes, requirements, or next actions..."
                  value={dealNotes}
                  onChange={(e) => setDealNotes(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 text-slate-900 dark:text-white"
                />
              </div>

              <div className="pt-2 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setShowAddDealModal(false)}
                  className="px-4 py-2 rounded-xl text-slate-500 hover:text-white font-bold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-6 py-2 bg-rose-600 hover:bg-rose-500 text-white font-extrabold rounded-xl shadow-md shadow-rose-600/30"
                >
                  Save Deal
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Add Task Modal */}
      {showAddTaskModal && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white dark:bg-zinc-950 rounded-3xl p-6 max-w-md w-full border border-slate-200 dark:border-zinc-800 shadow-2xl space-y-4 animate-fadeIn">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-zinc-900">
              <h3 className="font-black text-slate-900 dark:text-white text-lg">Create Follow-up Task</h3>
              <button onClick={() => setShowAddTaskModal(false)} className="p-1 rounded-full text-slate-400 hover:text-white">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleCreateTask} className="space-y-3 text-xs">
              <div>
                <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Task Title</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Call Alex re: pricing proposal"
                  value={taskTitle}
                  onChange={(e) => setTaskTitle(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 text-slate-900 dark:text-white"
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Due Date</label>
                  <input
                    type="date"
                    required
                    value={taskDueDate}
                    onChange={(e) => setTaskDueDate(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 font-mono text-slate-900 dark:text-white"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Priority</label>
                  <select
                    value={taskPriority}
                    onChange={(e) => setTaskPriority(e.target.value as any)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 text-slate-900 dark:text-white"
                  >
                    <option value="urgent">Urgent</option>
                    <option value="high">High</option>
                    <option value="normal">Normal</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Related Client (Optional)</label>
                <input
                  type="text"
                  placeholder="e.g. Acme Corp"
                  value={taskContact}
                  onChange={(e) => setTaskContact(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl px-3 py-2 text-slate-900 dark:text-white"
                />
              </div>

              <div className="pt-2 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setShowAddTaskModal(false)}
                  className="px-4 py-2 rounded-xl text-slate-500 hover:text-white font-bold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-6 py-2 bg-rose-600 hover:bg-rose-500 text-white font-extrabold rounded-xl shadow-md shadow-rose-600/30"
                >
                  Add Task
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
