import React, { useState, useEffect, useMemo } from 'react';
import { CRMContact, CRMStage, CurrencyCode, NormalizedRecord } from '../types';
import { formatCurrency } from '../utils/currencyFormatter';
import { calculatePipelineSummary, autoGenerateDealsFromRecords } from '../utils/crmEngine';
import { crmService } from '../services/crmService';
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip } from 'recharts';
import {
  Users,
  Plus,
  Search,
  Filter,
  Trash2,
  Mail,
  Phone,
  MapPin,
  Calendar,
  CheckCircle2,
  ArrowRight,
  Zap,
  RefreshCw,
  TrendingUp,
  PieChart as PieIcon,
  Award,
  Layers,
  FileSpreadsheet,
  X,
  ChevronRight,
  DollarSign,
} from 'lucide-react';

interface CRMViewProps {
  contacts: CRMContact[];
  onContactsChange: (contacts: CRMContact[]) => void;
  currency: CurrencyCode;
  records: NormalizedRecord[];
  activeBusinessId?: string;
}

const KANBAN_STAGES: { key: CRMStage; label: string; color: string; hexColor: string; probabilityPct: number }[] = [
  { key: 'lead', label: 'Lead', color: 'bg-zinc-800 text-zinc-300', hexColor: '#64748b', probabilityPct: 10 },
  { key: 'qualified', label: 'Qualified', color: 'bg-blue-950 text-blue-400 border-blue-900', hexColor: '#3b82f6', probabilityPct: 30 },
  { key: 'proposal', label: 'Proposal', color: 'bg-purple-950 text-purple-400 border-purple-900', hexColor: '#a855f7', probabilityPct: 60 },
  { key: 'negotiation', label: 'Negotiation', color: 'bg-amber-950 text-amber-400 border-amber-900', hexColor: '#f59e0b', probabilityPct: 80 },
  { key: 'closed_won', label: 'Won', color: 'bg-emerald-950 text-emerald-400 border-emerald-900', hexColor: '#10b981', probabilityPct: 100 },
  { key: 'closed_lost', label: 'Lost', color: 'bg-rose-950 text-rose-400 border-rose-900', hexColor: '#ef4444', probabilityPct: 0 },
];

export const CRMView: React.FC<CRMViewProps> = ({
  contacts,
  onContactsChange,
  currency,
  records,
  activeBusinessId,
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedContact, setSelectedContact] = useState<CRMContact | null>(null);
  const [showAddModal, setShowAddModal] = useState(false);
  const [stageFilter, setStageFilter] = useState<'all' | CRMStage>('all');

  // Form State
  const [newCompany, setNewCompany] = useState('');
  const [newName, setNewName] = useState('');
  const [newEmail, setNewEmail] = useState('');
  const [newPhone, setNewPhone] = useState('');
  const [newStage, setNewStage] = useState<CRMStage>('lead');
  const [newDealValue, setNewDealValue] = useState<number | ''>(10000);
  const [newTag, setNewTag] = useState('Enterprise');
  const [newNotes, setNewNotes] = useState('');

  // Auto-populate pipeline if currently empty
  useEffect(() => {
    if (contacts.length === 0 && records.length > 0) {
      const generated = autoGenerateDealsFromRecords(records);
      onContactsChange(generated);
    }
  }, [records, contacts.length]);

  const handleSyncDeals = () => {
    const generated = autoGenerateDealsFromRecords(records);
    onContactsChange(generated);
  };

  const pipelineSummary = calculatePipelineSummary(contacts);

  // Weighted Expected Pipeline Value
  const weightedPipelineValue = useMemo(() => {
    let sum = 0;
    contacts.forEach((c) => {
      const stageConfig = KANBAN_STAGES.find((s) => s.key === c.stage);
      const prob = stageConfig ? stageConfig.probabilityPct / 100 : 0.2;
      sum += (c.dealValue || 0) * prob;
    });
    return sum;
  }, [contacts]);

  // Stage distribution dataset for Donut Chart
  const donutData = useMemo(() => {
    return KANBAN_STAGES.map((s) => {
      const stageDeals = contacts.filter((c) => {
        if (s.key === 'lead') return c.stage === 'lead' || c.stage === 'in_touch';
        if (s.key === 'qualified') return c.stage === 'qualified' || c.stage === 'offer_sent';
        if (s.key === 'proposal') return c.stage === 'proposal' || c.stage === 'discussion';
        return c.stage === s.key;
      });
      const count = stageDeals.length;
      const totalVal = stageDeals.reduce((acc, d) => acc + (d.dealValue || 0), 0);
      return {
        name: s.label,
        value: count,
        totalVal,
        color: s.hexColor,
      };
    }).filter((d) => d.value > 0);
  }, [contacts]);

  // Advance deal to next stage
  const handleAdvanceStage = (contactId: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    const stageOrder: CRMStage[] = ['lead', 'qualified', 'proposal', 'negotiation', 'closed_won'];
    const updated = contacts.map((c) => {
      if (c.id !== contactId) return c;
      const currIdx = stageOrder.indexOf(c.stage);
      if (currIdx >= 0 && currIdx < stageOrder.length - 1) {
        const nextStage = stageOrder[currIdx + 1];
        if (activeBusinessId) {
          crmService.updateDealStage(activeBusinessId, c.id, nextStage);
        }
        return { ...c, stage: nextStage };
      }
      return c;
    });
    onContactsChange(updated);
  };

  // Move deal to specific stage
  const handleMoveStage = (contactId: string, targetStage: CRMStage) => {
    const updated = contacts.map((c) => {
      if (c.id !== contactId) return c;
      if (activeBusinessId) {
        crmService.updateDealStage(activeBusinessId, c.id, targetStage);
      }
      return { ...c, stage: targetStage };
    });
    onContactsChange(updated);
    if (selectedContact && selectedContact.id === contactId) {
      setSelectedContact({ ...selectedContact, stage: targetStage });
    }
  };

  // Delete Deal
  const handleDeleteDeal = (contactId: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    if (window.confirm('Delete this deal from the pipeline?')) {
      const updated = contacts.filter((c) => c.id !== contactId);
      onContactsChange(updated);
      if (activeBusinessId) {
        crmService.deleteDeal(activeBusinessId, contactId);
      }
      if (selectedContact && selectedContact.id === contactId) {
        setSelectedContact(null);
      }
    }
  };

  // Handle Add Deal
  const handleCreateDeal = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newName.trim() && !newCompany.trim()) return;

    const val = Number(newDealValue) || 5000;
    const newDeal: CRMContact = {
      id: `deal-${Date.now()}`,
      name: newName.trim() || newCompany.trim(),
      company: newCompany.trim() || newName.trim(),
      email: newEmail.trim() || 'contact@client.com',
      phone: newPhone.trim() || '+1 (555) 019-2831',
      stage: newStage,
      dealValue: val,
      tags: [newTag],
      notes: newNotes.trim() || 'Created via Sales Pipeline CRM',
      lastContactDate: new Date().toISOString().split('T')[0],
      createdAt: new Date().toISOString().split('T')[0],
      totalSpent: val,
      orderCount: 1,
    };

    if (activeBusinessId) {
      await crmService.createDeal(activeBusinessId, {
        name: newDeal.name,
        company: newDeal.company,
        email: newDeal.email,
        phone: newDeal.phone,
        stage: newDeal.stage,
        dealValue: newDeal.dealValue,
        tags: newDeal.tags,
        notes: newDeal.notes,
      });
    }

    onContactsChange([newDeal, ...contacts]);
    setShowAddModal(false);
    setNewCompany('');
    setNewName('');
    setNewEmail('');
    setNewPhone('');
    setNewNotes('');
  };

  // Export Pipeline to CSV
  const handleExportCSV = () => {
    if (contacts.length === 0) return;
    const headers = ['Company', 'Contact Name', 'Email', 'Phone', 'Stage', 'Deal Value', 'Tags', 'Last Contact'];
    const rows = contacts.map((c) => [
      `"${(c.company || '').replace(/"/g, '""')}"`,
      `"${(c.name || '').replace(/"/g, '""')}"`,
      `"${c.email || ''}"`,
      `"${c.phone || ''}"`,
      `"${c.stage}"`,
      c.dealValue || 0,
      `"${(c.tags || []).join('; ')}"`,
      `"${c.lastContactDate || ''}"`,
    ]);

    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map((e) => e.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `databeta-crm-deals-${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const filteredContacts = useMemo(() => {
    let result = contacts;
    if (stageFilter !== 'all') {
      result = result.filter((c) => c.stage === stageFilter);
    }
    if (searchTerm.trim()) {
      const q = searchTerm.toLowerCase().trim();
      result = result.filter(
        (c) =>
          c.name.toLowerCase().includes(q) ||
          c.company.toLowerCase().includes(q) ||
          (c.email && c.email.toLowerCase().includes(q))
      );
    }
    return result;
  }, [contacts, stageFilter, searchTerm]);

  return (
    <div className="space-y-6 animate-fadeIn">
      {/* Header Banner */}
      <div className="bg-white dark:bg-zinc-950 text-slate-900 dark:text-white p-7 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-bold text-rose-600 dark:text-rose-500 uppercase tracking-widest mb-1">
            <TrendingUp className="w-4 h-4 text-rose-600" />
            <span>Revenue Pipeline & CRM</span>
          </div>
          <h2 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight">Sales Pipeline Studio</h2>
          <p className="text-xs text-slate-500 dark:text-zinc-400 mt-1 max-w-xl">
            Track active opportunities, forecast weighted revenue, manage client communications, and advance deals through the Kanban stages.
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={() => setShowAddModal(true)}
            className="px-5 py-2.5 bg-rose-600 hover:bg-rose-500 text-white font-extrabold text-xs rounded-full shadow-md shadow-rose-600/30 flex items-center gap-2 transition-all active:scale-95"
          >
            <Plus className="w-4 h-4" />
            <span>New Opportunity</span>
          </button>

          <button
            onClick={handleExportCSV}
            className="px-4 py-2.5 bg-slate-100 dark:bg-zinc-900 hover:bg-slate-200 dark:hover:bg-zinc-800 text-slate-800 dark:text-zinc-200 font-extrabold text-xs rounded-full border border-slate-200 dark:border-zinc-800 flex items-center gap-2 transition-all active:scale-95"
          >
            <FileSpreadsheet className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
            <span>Export Deals</span>
          </button>

          <button
            onClick={handleSyncDeals}
            title="Auto-sync opportunities from customer transactions"
            className="p-2.5 bg-slate-100 dark:bg-zinc-900 hover:bg-slate-200 dark:hover:bg-zinc-800 text-slate-700 dark:text-zinc-300 rounded-full border border-slate-200 dark:border-zinc-800 transition-all active:scale-95"
          >
            <RefreshCw className="w-4 h-4 text-slate-500" />
          </button>
        </div>
      </div>

      {/* 4 Pipeline Stat KPI Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="bg-white dark:bg-zinc-950 p-5 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs space-y-1">
          <div className="text-[10px] font-bold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">Total Pipeline Value</div>
          <div className="text-2xl font-black text-slate-900 dark:text-white">
            {formatCurrency(pipelineSummary.totalPipelineValue, currency)}
          </div>
          <p className="text-[10px] text-slate-400 dark:text-zinc-500">{contacts.length} total opportunities</p>
        </div>

        <div className="bg-white dark:bg-zinc-950 p-5 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs space-y-1">
          <div className="text-[10px] font-bold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">Weighted Expected Revenue</div>
          <div className="text-2xl font-black text-emerald-600 dark:text-emerald-400">
            {formatCurrency(weightedPipelineValue, currency)}
          </div>
          <p className="text-[10px] text-slate-400 dark:text-zinc-500">Probability adjusted</p>
        </div>

        <div className="bg-white dark:bg-zinc-950 p-5 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs space-y-1">
          <div className="text-[10px] font-bold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">Won Revenue (Realized)</div>
          <div className="text-2xl font-black text-rose-600 dark:text-rose-500">
            {formatCurrency(
              contacts
                .filter((c) => c.stage === 'closed_won')
                .reduce((acc, c) => acc + (c.dealValue || 0), 0),
              currency
            )}
          </div>
          <p className="text-[10px] text-slate-400 dark:text-zinc-500">Closed contracts</p>
        </div>

        <div className="bg-white dark:bg-zinc-950 p-5 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs space-y-1">
          <div className="text-[10px] font-bold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">Win Rate Conversion</div>
          <div className="text-2xl font-black text-indigo-600 dark:text-indigo-400">
            {pipelineSummary.winRatePct.toFixed(1)}%
          </div>
          <p className="text-[10px] text-slate-400 dark:text-zinc-500">Proposal to Won ratio</p>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white dark:bg-zinc-950 p-4 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs flex flex-col sm:flex-row items-center justify-between gap-3">
        <div className="relative w-full sm:max-w-md">
          <Search className="w-4 h-4 text-slate-400 dark:text-zinc-500 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search deals by company, contact or email..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-full pl-9 pr-4 py-2 text-xs text-slate-900 dark:text-white font-medium focus:outline-none focus:ring-2 focus:ring-rose-500"
          />
        </div>

        <div className="flex items-center gap-1.5 overflow-x-auto text-xs w-full sm:w-auto">
          <button
            onClick={() => setStageFilter('all')}
            className={`px-3 py-1.5 rounded-full font-bold transition-all ${
              stageFilter === 'all'
                ? 'bg-rose-600 text-white shadow-xs'
                : 'bg-slate-100 dark:bg-zinc-900 text-slate-600 dark:text-zinc-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            All Stages ({contacts.length})
          </button>
          {KANBAN_STAGES.map((s) => {
            const count = contacts.filter((c) => c.stage === s.key).length;
            return (
              <button
                key={s.key}
                onClick={() => setStageFilter(s.key)}
                className={`px-3 py-1.5 rounded-full font-bold transition-all ${
                  stageFilter === s.key
                    ? 'bg-rose-600 text-white shadow-xs'
                    : 'bg-slate-100 dark:bg-zinc-900 text-slate-600 dark:text-zinc-400 hover:text-slate-900 dark:hover:text-white'
                }`}
              >
                {s.label} ({count})
              </button>
            );
          })}
        </div>
      </div>

      {/* Kanban Board Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-3">
        {KANBAN_STAGES.map((stage) => {
          const stageDeals = contacts.filter((c) => {
            if (stage.key === 'lead') return c.stage === 'lead' || c.stage === 'in_touch';
            if (stage.key === 'qualified') return c.stage === 'qualified' || c.stage === 'offer_sent';
            if (stage.key === 'proposal') return c.stage === 'proposal' || c.stage === 'discussion';
            return c.stage === stage.key;
          });

          const stageTotal = stageDeals.reduce((acc, d) => acc + (d.dealValue || 0), 0);

          return (
            <div
              key={stage.key}
              className="bg-slate-100/60 dark:bg-zinc-900/40 rounded-3xl p-3.5 border border-slate-200/80 dark:border-zinc-800/80 flex flex-col space-y-3 min-h-[420px]"
            >
              {/* Column Header */}
              <div className="flex items-center justify-between pb-2 border-b border-slate-200 dark:border-zinc-800">
                <div className="flex items-center gap-2">
                  <div
                    className="w-2.5 h-2.5 rounded-full"
                    style={{ backgroundColor: stage.hexColor }}
                  />
                  <span className="font-extrabold text-xs text-slate-900 dark:text-white">
                    {stage.label}
                  </span>
                  <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-slate-200 dark:bg-zinc-800 text-slate-600 dark:text-zinc-400 font-mono font-bold">
                    {stageDeals.length}
                  </span>
                </div>
                <span className="text-[10px] font-mono font-bold text-slate-500 dark:text-zinc-400">
                  {formatCurrency(stageTotal, currency)}
                </span>
              </div>

              {/* Deal Cards Container */}
              <div className="flex-1 space-y-2.5 overflow-y-auto max-h-[600px] pr-0.5 custom-scrollbar">
                {stageDeals.map((deal) => (
                  <div
                    key={deal.id}
                    onClick={() => setSelectedContact(deal)}
                    className="p-3.5 rounded-2xl bg-white dark:bg-zinc-950 border border-slate-200/80 dark:border-zinc-800/80 shadow-xs hover:border-rose-500/60 cursor-pointer transition-all space-y-2 group"
                  >
                    <div className="flex items-start justify-between gap-1">
                      <div className="font-bold text-xs text-slate-900 dark:text-white truncate">
                        {deal.company || deal.name}
                      </div>
                      <button
                        onClick={(e) => handleDeleteDeal(deal.id, e)}
                        className="opacity-0 group-hover:opacity-100 text-slate-400 hover:text-rose-600 transition-opacity p-0.5"
                        title="Delete Deal"
                      >
                        <Trash2 className="w-3 h-3" />
                      </button>
                    </div>

                    <div className="text-[11px] text-slate-500 dark:text-zinc-400 truncate">
                      {deal.name}
                    </div>

                    <div className="flex items-center justify-between pt-1 border-t border-slate-100 dark:border-zinc-900 text-xs">
                      <span className="font-black text-rose-600 dark:text-rose-400 font-mono">
                        {formatCurrency(deal.dealValue || 0, currency)}
                      </span>
                      {stage.key !== 'closed_won' && stage.key !== 'closed_lost' && (
                        <button
                          onClick={(e) => handleAdvanceStage(deal.id, e)}
                          title="Advance to next stage"
                          className="px-2 py-0.5 rounded-full bg-slate-100 dark:bg-zinc-800 text-slate-700 dark:text-zinc-300 hover:bg-rose-600 hover:text-white text-[10px] font-bold transition-colors inline-flex items-center gap-0.5"
                        >
                          <span>Advance</span>
                          <ChevronRight className="w-2.5 h-2.5" />
                        </button>
                      )}
                    </div>
                  </div>
                ))}

                {stageDeals.length === 0 && (
                  <div className="h-32 border-2 border-dashed border-slate-200 dark:border-zinc-800 rounded-2xl flex items-center justify-center text-[11px] text-slate-400 dark:text-zinc-600 font-medium">
                    No deals in {stage.label}
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Create Opportunity Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white dark:bg-zinc-950 text-slate-900 dark:text-white rounded-3xl border border-slate-200 dark:border-zinc-800 shadow-2xl max-w-md w-full p-6 relative space-y-4 animate-fadeIn">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-zinc-900">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-xl bg-rose-600 text-white flex items-center justify-center font-bold">
                  <Plus className="w-4 h-4" />
                </div>
                <h3 className="font-bold text-base">New Sales Opportunity</h3>
              </div>
              <button
                onClick={() => setShowAddModal(false)}
                className="p-1 rounded-full text-slate-400 hover:text-slate-900 dark:hover:text-white"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={handleCreateDeal} className="space-y-4 text-xs">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Company Name</label>
                  <input
                    type="text"
                    required
                    autoFocus
                    placeholder="e.g. Apex Global"
                    value={newCompany}
                    onChange={(e) => setNewCompany(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl px-3.5 py-2 text-xs text-slate-900 dark:text-white font-medium focus:outline-none focus:ring-2 focus:ring-rose-500"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Primary Contact</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Sarah Jenkins"
                    value={newName}
                    onChange={(e) => setNewName(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl px-3.5 py-2 text-xs text-slate-900 dark:text-white font-medium focus:outline-none focus:ring-2 focus:ring-rose-500"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Deal Value ({currency})</label>
                  <input
                    type="number"
                    step="100"
                    required
                    value={newDealValue}
                    onChange={(e) => setNewDealValue(e.target.value === '' ? '' : Number(e.target.value))}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl px-3.5 py-2 font-mono font-bold text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-rose-500"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Pipeline Stage</label>
                  <select
                    value={newStage}
                    onChange={(e) => setNewStage(e.target.value as CRMStage)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl px-3.5 py-2 font-bold text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-rose-500"
                  >
                    {KANBAN_STAGES.map((s) => (
                      <option key={s.key} value={s.key}>
                        {s.label} ({s.probabilityPct}%)
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Email</label>
                  <input
                    type="email"
                    placeholder="sarah@apex.com"
                    value={newEmail}
                    onChange={(e) => setNewEmail(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl px-3.5 py-2 text-xs text-slate-900 dark:text-white font-medium focus:outline-none focus:ring-2 focus:ring-rose-500"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Phone</label>
                  <input
                    type="tel"
                    placeholder="+1 (555) 019-2831"
                    value={newPhone}
                    onChange={(e) => setNewPhone(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl px-3.5 py-2 text-xs text-slate-900 dark:text-white font-medium focus:outline-none focus:ring-2 focus:ring-rose-500"
                  />
                </div>
              </div>

              <div>
                <label className="block font-bold text-slate-700 dark:text-zinc-300 mb-1">Strategic Notes</label>
                <textarea
                  rows={2}
                  placeholder="Key pain points, contract terms, next meeting schedule..."
                  value={newNotes}
                  onChange={(e) => setNewNotes(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl px-3.5 py-2 text-xs text-slate-900 dark:text-white font-medium focus:outline-none focus:ring-2 focus:ring-rose-500"
                />
              </div>

              <div className="pt-2 flex items-center justify-end gap-2 border-t border-slate-100 dark:border-zinc-900">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-4 py-2 rounded-full text-slate-500 dark:text-zinc-400 font-bold hover:text-slate-900 dark:hover:text-white"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-6 py-2 bg-rose-600 hover:bg-rose-500 text-white font-extrabold rounded-full shadow-md shadow-rose-600/30 transition-all"
                >
                  Create Deal
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Selected Deal Detail Drawer */}
      {selectedContact && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-end p-0 sm:p-4">
          <div className="bg-white dark:bg-zinc-950 text-slate-900 dark:text-white w-full sm:max-w-md h-full sm:h-[90vh] sm:rounded-3xl shadow-2xl border border-slate-200 dark:border-zinc-800 p-6 flex flex-col justify-between overflow-y-auto animate-slideInRight">
            <div className="space-y-6">
              <div className="flex items-center justify-between pb-4 border-b border-slate-100 dark:border-zinc-900">
                <div>
                  <h3 className="font-black text-lg text-slate-900 dark:text-white">{selectedContact.company}</h3>
                  <p className="text-xs text-slate-500 dark:text-zinc-400">{selectedContact.name}</p>
                </div>
                <button
                  onClick={() => setSelectedContact(null)}
                  className="p-1 rounded-full text-slate-400 hover:text-slate-900 dark:hover:text-white"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Deal Value Callout */}
              <div className="p-4 rounded-2xl bg-slate-50 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 flex items-center justify-between">
                <div>
                  <span className="text-[10px] font-bold uppercase text-slate-400">Deal Value</span>
                  <div className="text-2xl font-black text-rose-600 dark:text-rose-400 font-mono">
                    {formatCurrency(selectedContact.dealValue || 0, currency)}
                  </div>
                </div>
                <span className="px-3 py-1 rounded-full bg-rose-50 dark:bg-rose-950/40 text-rose-600 dark:text-rose-400 font-extrabold text-xs">
                  {selectedContact.stage.toUpperCase()}
                </span>
              </div>

              {/* Change Stage */}
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-zinc-300 mb-2">Advance Deal Stage</label>
                <div className="grid grid-cols-2 gap-2">
                  {KANBAN_STAGES.map((s) => (
                    <button
                      key={s.key}
                      onClick={() => handleMoveStage(selectedContact.id, s.key)}
                      className={`p-2.5 rounded-xl border text-xs font-bold transition-all text-left flex items-center justify-between ${
                        selectedContact.stage === s.key
                          ? 'border-rose-600 bg-rose-50/40 dark:bg-rose-950/20 text-rose-600 font-extrabold'
                          : 'border-slate-200 dark:border-zinc-800 bg-slate-50 dark:bg-zinc-900 text-slate-600 dark:text-zinc-400'
                      }`}
                    >
                      <span>{s.label}</span>
                      <span className="text-[10px] font-mono opacity-60">{s.probabilityPct}%</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Contact Information */}
              <div className="space-y-3 text-xs">
                <h4 className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Contact Info</h4>
                <div className="p-3 bg-slate-50 dark:bg-zinc-900 rounded-xl flex items-center gap-3">
                  <Mail className="w-4 h-4 text-rose-600" />
                  <span className="font-medium text-slate-900 dark:text-white">{selectedContact.email || 'No email provided'}</span>
                </div>
                <div className="p-3 bg-slate-50 dark:bg-zinc-900 rounded-xl flex items-center gap-3">
                  <Phone className="w-4 h-4 text-rose-600" />
                  <span className="font-medium text-slate-900 dark:text-white">{selectedContact.phone || 'No phone recorded'}</span>
                </div>
              </div>

              {/* Notes */}
              <div className="space-y-2 text-xs">
                <h4 className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Notes & Activity</h4>
                <div className="p-3.5 bg-slate-50 dark:bg-zinc-900 rounded-xl text-slate-700 dark:text-zinc-300 leading-relaxed">
                  {selectedContact.notes || 'No strategic notes added yet.'}
                </div>
              </div>
            </div>

            <div className="pt-4 border-t border-slate-100 dark:border-zinc-900 flex justify-between">
              <button
                onClick={(e) => handleDeleteDeal(selectedContact.id, e)}
                className="px-4 py-2 text-rose-600 font-bold hover:bg-rose-50 dark:hover:bg-rose-950/40 rounded-full text-xs flex items-center gap-1.5 transition-colors"
              >
                <Trash2 className="w-3.5 h-3.5" />
                <span>Delete Deal</span>
              </button>

              <button
                onClick={() => setSelectedContact(null)}
                className="px-6 py-2 bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-extrabold rounded-full text-xs"
              >
                Close Drawer
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
