import { Deal, CRMPipelineSummary, CRMStage, NormalizedRecord } from '../types';

export function calculatePipelineSummary(deals: Deal[]): CRMPipelineSummary {
  let totalPipelineValue = 0;
  let closedWonCount = 0;
  const stageCounts: Record<string, number> = {
    lead: 0,
    qualified: 0,
    discovery: 0,
    proposal_sent: 0,
    negotiation: 0,
    won: 0,
    lost: 0,
  };

  for (const d of deals) {
    const val = d.amount || d.dealValue || 0;
    totalPipelineValue += val;
    stageCounts[d.stage] = (stageCounts[d.stage] || 0) + 1;
    if (d.stage === 'won' || (d.stage as any) === 'closed_won') {
      closedWonCount++;
    }
  }

  const totalDeals = deals.length;
  const winRatePct = totalDeals > 0 ? (closedWonCount / totalDeals) * 100 : 0;
  const avgDealSize = totalDeals > 0 ? totalPipelineValue / totalDeals : 0;

  return {
    totalPipelineValue,
    totalDeals,
    winRatePct,
    avgDealSize,
    stageCounts,
  };
}

export function autoGenerateDealsFromRecords(records: NormalizedRecord[]): Deal[] {
  if (!records || records.length === 0) {
    return [
      {
        id: 'crm-demo-1',
        workspaceId: 'ws-demo',
        title: 'Acme — Enterprise Cloud License',
        companyName: 'Acme Corporation',
        company: 'Acme Corporation',
        contactName: 'Alex Vance',
        name: 'Alex Vance',
        contactEmail: 'alex@acmecorp.com',
        email: 'alex@acmecorp.com',
        contactPhone: '+1 (555) 234-5678',
        phone: '+1 (555) 234-5678',
        stage: 'proposal_sent',
        amount: 45000,
        dealValue: 45000,
        currency: 'USD',
        expectedCloseDate: '2026-03-31',
        probabilityPct: 70,
        tags: ['Enterprise', 'Priority'],
        notes: 'Requested Q3 enterprise software expansion proposal.',
        lastContactDate: 'Today',
        createdAt: new Date().toISOString().substring(0, 10),
        updatedAt: new Date().toISOString(),
        totalSpent: 45000,
        orderCount: 3,
      },
    ];
  }

  const customerMap: Record<string, { totalSpent: number; count: number; lastDate: string }> = {};

  records.forEach((r) => {
    const name = (r.customer || r.category || 'Enterprise Account').trim();
    const rev = r.revenue || 0;
    if (!customerMap[name]) {
      customerMap[name] = { totalSpent: 0, count: 0, lastDate: r.dateString || 'Recently' };
    }
    customerMap[name].totalSpent += rev;
    customerMap[name].count += 1;
  });

  const stages: Deal['stage'][] = ['won', 'proposal_sent', 'negotiation', 'qualified', 'lead'];

  return Object.entries(customerMap).map(([compName, data], idx) => {
    const stage = stages[idx % stages.length];
    return {
      id: `crm-auto-${idx}-${Date.now()}`,
      workspaceId: 'ws-auto',
      title: `${compName} — Expansion Deal`,
      companyName: compName,
      company: compName,
      contactName: `${compName} Representative`,
      name: `${compName} Representative`,
      contactEmail: `contact@${compName.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`,
      email: `contact@${compName.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`,
      contactPhone: '+1 (555) 000-0000',
      phone: '+1 (555) 000-0000',
      stage,
      amount: data.totalSpent > 0 ? data.totalSpent : 15000,
      dealValue: data.totalSpent > 0 ? data.totalSpent : 15000,
      currency: 'USD',
      expectedCloseDate: '2026-04-15',
      probabilityPct: stage === 'won' ? 100 : stage === 'negotiation' ? 85 : stage === 'proposal_sent' ? 70 : 30,
      tags: ['Transaction Synced'],
      notes: `Auto-generated deal based on ${data.count} historical order records.`,
      lastContactDate: data.lastDate,
      createdAt: new Date().toISOString().substring(0, 10),
      updatedAt: new Date().toISOString(),
      totalSpent: data.totalSpent,
      orderCount: data.count,
    };
  });
}
