import { CRMContact, CRMPipelineSummary, CRMStage, NormalizedRecord } from '../types';

export function calculatePipelineSummary(contacts: CRMContact[]): CRMPipelineSummary {
  let totalPipelineValue = 0;
  let closedWonCount = 0;
  const stageCounts: Record<CRMStage, number> = {
    lead: 0,
    qualified: 0,
    proposal: 0,
    negotiation: 0,
    closed_won: 0,
    closed_lost: 0,
    in_touch: 0,
    offer_sent: 0,
    discussion: 0,
  };

  for (const c of contacts) {
    totalPipelineValue += c.dealValue || 0;
    stageCounts[c.stage] = (stageCounts[c.stage] || 0) + 1;
    if (c.stage === 'closed_won') {
      closedWonCount++;
    }
  }

  const totalDeals = contacts.length;
  const winRatePct = totalDeals > 0 ? (closedWonCount / totalDeals) * 100 : 0;
  const avgDealSize = totalDeals > 0 ? totalPipelineValue / totalDeals : 0;

  return {
    totalPipelineValue,
    totalDeals,
    winRatePct,
    avgDealSize,
    stageCounts,
  };
}

/**
 * Intelligent CRM Auto-Generation: Derives high-value sales opportunities directly from uploaded customer transactions.
 */
export function autoGenerateDealsFromRecords(records: NormalizedRecord[]): CRMContact[] {
  if (!records || records.length === 0) {
    return [
      {
        id: 'crm-demo-1',
        company: 'Acme Corporation',
        name: 'Alex Vance',
        email: 'alex@acmecorp.com',
        phone: '+1 (555) 234-5678',
        stage: 'proposal',
        dealValue: 45000,
        tags: ['Enterprise', 'Priority'],
        notes: 'Requested Q3 enterprise software expansion proposal.',
        lastContactDate: 'Today',
        createdAt: new Date().toISOString().substring(0, 10),
        totalSpent: 45000,
        orderCount: 3,
      },
      {
        id: 'crm-demo-2',
        company: 'Starlight Media',
        name: 'Sarah Connor',
        email: 'sarah@starlight.io',
        phone: '+1 (555) 876-5432',
        stage: 'negotiation',
        dealValue: 28000,
        tags: ['Retainer'],
        notes: 'Finalizing 12-month annual retainer contract.',
        lastContactDate: 'Yesterday',
        createdAt: new Date().toISOString().substring(0, 10),
        totalSpent: 28000,
        orderCount: 2,
      },
      {
        id: 'crm-demo-3',
        company: 'Apex Logistics',
        name: 'Michael Chang',
        email: 'm.chang@apexlogistics.com',
        phone: '+1 (555) 345-6789',
        stage: 'qualified',
        dealValue: 18500,
        tags: ['Growth'],
        notes: 'Completed technical discovery call. Needs custom API integration.',
        lastContactDate: '3 days ago',
        createdAt: new Date().toISOString().substring(0, 10),
        totalSpent: 18500,
        orderCount: 1,
      },
      {
        id: 'crm-demo-4',
        company: 'Nexus Software',
        name: 'Elena Rostova',
        email: 'elena@nexussoft.com',
        phone: '+1 (555) 901-2345',
        stage: 'closed_won',
        dealValue: 62000,
        tags: ['Closed Won'],
        notes: 'Annual license agreement signed & paid in full.',
        lastContactDate: '5 days ago',
        createdAt: new Date().toISOString().substring(0, 10),
        totalSpent: 62000,
        orderCount: 4,
      },
    ];
  }

  const customerMap: Record<string, { totalSpent: number; count: number; lastDate: string }> = {};

  records.forEach((r) => {
    const name = (r.customer || r.category || 'Enterprise Account').trim();
    const rev = r.revenue || 0;
    if (!customerMap[name]) {
      customerMap[name] = { totalSpent: 0, count: 0, lastDate: r.dateString || 'Recently' };
    }
    customerMap[name].totalSpent += rev;
    customerMap[name].count += 1;
  });

  const stages: CRMStage[] = ['closed_won', 'proposal', 'negotiation', 'qualified', 'lead'];

  return Object.entries(customerMap).map(([compName, data], idx) => {
    const stage = stages[idx % stages.length];
    return {
      id: `crm-auto-${idx}-${Date.now()}`,
      company: compName,
      name: `${compName} Representative`,
      email: `contact@${compName.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`,
      phone: '+1 (555) 000-0000',
      stage,
      dealValue: data.totalSpent > 0 ? data.totalSpent : 15000,
      tags: ['Transaction Synced'],
      notes: `Auto-generated deal based on ${data.count} historical order records.`,
      lastContactDate: data.lastDate,
      createdAt: new Date().toISOString().substring(0, 10),
      totalSpent: data.totalSpent,
      orderCount: data.count,
    };
  });
}
