// ============================================================================
// DataBeta: Isolated Labeled Demo Dataset
// Non-negotiable rule: Demo data is strictly isolated and clearly labeled.
// ============================================================================

import {
  Deal,
  Contact,
  Company,
  Task,
  Invoice,
  Transaction,
  NormalizedRecord,
} from '../types';

export const DEMO_WORKSPACE_ID = 'demo-workspace-apex';

export const DEMO_COMPANIES: Company[] = [
  {
    id: 'demo-comp-1',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Nexus Dynamics',
    domain: 'nexusdynamics.com',
    industry: 'Enterprise SaaS',
    tier: 'Enterprise',
    phone: '+1 (555) 234-5678',
    website: 'https://nexusdynamics.com',
    address: 'Austin, TX',
    totalWonRevenue: 45000,
    openPipelineValue: 85000,
    contactsCount: 2,
    createdAt: '2026-01-10',
    updatedAt: '2026-02-01',
  },
  {
    id: 'demo-comp-2',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Vanguard Logistics',
    domain: 'vanguardlogistics.com',
    industry: 'Supply Chain & Freight',
    tier: 'Enterprise',
    phone: '+1 (555) 345-6789',
    website: 'https://vanguardlogistics.com',
    address: 'Chicago, IL',
    totalWonRevenue: 32000,
    openPipelineValue: 64000,
    contactsCount: 1,
    createdAt: '2026-01-15',
    updatedAt: '2026-02-10',
  },
  {
    id: 'demo-comp-3',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Horizon Digital Media',
    domain: 'horizondigital.io',
    industry: 'Creative & Performance Marketing',
    tier: 'Mid-Market',
    phone: '+1 (555) 456-7890',
    website: 'https://horizondigital.io',
    address: 'New York, NY',
    totalWonRevenue: 18000,
    openPipelineValue: 28000,
    contactsCount: 1,
    createdAt: '2026-01-20',
    updatedAt: '2026-02-12',
  },
  {
    id: 'demo-comp-4',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Cobalt BioTech',
    domain: 'cobaltbiotech.org',
    industry: 'Healthcare & Diagnostics',
    tier: 'Enterprise',
    phone: '+1 (555) 567-8901',
    website: 'https://cobaltbiotech.org',
    address: 'Boston, MA',
    totalWonRevenue: 60000,
    openPipelineValue: 120000,
    contactsCount: 1,
    createdAt: '2026-01-05',
    updatedAt: '2026-02-14',
  },
];

export const DEMO_CONTACTS: Contact[] = [
  {
    id: 'demo-cont-1',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Sarah Chen',
    email: 'schen@nexusdynamics.com',
    phone: '+1 (555) 234-5678',
    companyId: 'demo-comp-1',
    companyName: 'Nexus Dynamics',
    roleTitle: 'VP of Engineering',
    tags: ['Key Decision Maker', 'Q1 Priority'],
    notes: 'Requested security compliance questionnaire before contract signature.',
    lastActivityAt: '2026-02-11',
    createdAt: '2026-01-10',
    updatedAt: '2026-02-11',
  },
  {
    id: 'demo-cont-2',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Marcus Brody',
    email: 'mbrody@vanguardlogistics.com',
    phone: '+1 (555) 345-6789',
    companyId: 'demo-comp-2',
    companyName: 'Vanguard Logistics',
    roleTitle: 'Chief Operating Officer',
    tags: ['Procurement', 'High Value'],
    notes: 'Evaluating warehouse integration milestone plan.',
    lastActivityAt: '2026-02-09',
    createdAt: '2026-01-15',
    updatedAt: '2026-02-09',
  },
  {
    id: 'demo-cont-3',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Elena Rostova',
    email: 'elena@horizondigital.io',
    phone: '+1 (555) 456-7890',
    companyId: 'demo-comp-3',
    companyName: 'Horizon Digital Media',
    roleTitle: 'Managing Partner',
    tags: ['Agency', 'Fast Mover'],
    notes: 'Proposal sent 4 days ago. Needs follow-up call on onboarding schedule.',
    lastActivityAt: '2026-02-08',
    createdAt: '2026-01-20',
    updatedAt: '2026-02-08',
  },
  {
    id: 'demo-cont-4',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'David Sterling',
    email: 'dsterling@cobaltbiotech.org',
    phone: '+1 (555) 567-8901',
    companyId: 'demo-comp-4',
    companyName: 'Cobalt BioTech',
    roleTitle: 'Director of Analytics',
    tags: ['Enterprise Deal', 'Security Review'],
    notes: 'Final contract in legal review. Target close next Friday.',
    lastActivityAt: '2026-02-13',
    createdAt: '2026-01-05',
    updatedAt: '2026-02-13',
  },
];

export const DEMO_DEALS: Deal[] = [
  {
    id: 'demo-deal-1',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Nexus Dynamics — Enterprise Platform License',
    companyId: 'demo-comp-1',
    companyName: 'Nexus Dynamics',
    contactId: 'demo-cont-1',
    contactName: 'Sarah Chen',
    contactEmail: 'schen@nexusdynamics.com',
    contactPhone: '+1 (555) 234-5678',
    stage: 'negotiation',
    amount: 85000,
    currency: 'USD',
    expectedCloseDate: '2026-02-28',
    probabilityPct: 85,
    source: 'Inbound Demo',
    ownerName: 'Alex Rivera',
    nextStep: 'Final MSA review with legal counsel',
    lastActivityAt: '2026-02-11',
    tags: ['Tier-1 Enterprise', 'Q1 Close'],
    createdAt: '2026-01-10',
    updatedAt: '2026-02-11',
  },
  {
    id: 'demo-deal-2',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Vanguard Logistics — Multi-Hub Implementation',
    companyId: 'demo-comp-2',
    companyName: 'Vanguard Logistics',
    contactId: 'demo-cont-2',
    contactName: 'Marcus Brody',
    contactEmail: 'mbrody@vanguardlogistics.com',
    contactPhone: '+1 (555) 345-6789',
    stage: 'proposal_sent',
    amount: 64000,
    currency: 'USD',
    expectedCloseDate: '2026-03-15',
    probabilityPct: 70,
    source: 'Referral',
    ownerName: 'Alex Rivera',
    nextStep: 'Follow up on proposal review meeting',
    lastActivityAt: '2026-02-09',
    tags: ['Supply Chain', 'Multi-Year'],
    createdAt: '2026-01-15',
    updatedAt: '2026-02-09',
  },
  {
    id: 'demo-deal-3',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Horizon Digital — Performance Analytics Package',
    companyId: 'demo-comp-3',
    companyName: 'Horizon Digital Media',
    contactId: 'demo-cont-3',
    contactName: 'Elena Rostova',
    contactEmail: 'elena@horizondigital.io',
    contactPhone: '+1 (555) 456-7890',
    stage: 'proposal_sent',
    amount: 28000,
    currency: 'USD',
    expectedCloseDate: '2026-02-20',
    probabilityPct: 70,
    source: 'Outbound Campaign',
    ownerName: 'Alex Rivera',
    nextStep: 'Send revised scope breakdown with onboarding timeline',
    lastActivityAt: '2026-02-08',
    tags: ['Agency Tier', 'Fast Close'],
    createdAt: '2026-01-20',
    updatedAt: '2026-02-08',
  },
  {
    id: 'demo-deal-4',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Cobalt BioTech — Diagnostic Pipeline Suite',
    companyId: 'demo-comp-4',
    companyName: 'Cobalt BioTech',
    contactId: 'demo-cont-4',
    contactName: 'David Sterling',
    contactEmail: 'dsterling@cobaltbiotech.org',
    contactPhone: '+1 (555) 567-8901',
    stage: 'negotiation',
    amount: 120000,
    currency: 'USD',
    expectedCloseDate: '2026-02-27',
    probabilityPct: 90,
    source: 'Executive Referral',
    ownerName: 'Alex Rivera',
    nextStep: 'Execute final order form upon board signoff',
    lastActivityAt: '2026-02-13',
    tags: ['Flagship Account', 'Healthcare'],
    createdAt: '2026-01-05',
    updatedAt: '2026-02-13',
  },
  {
    id: 'demo-deal-5',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Apex Dynamics — Annual Retainer Renewals',
    companyName: 'Apex Dynamics',
    stage: 'won',
    amount: 95000,
    currency: 'USD',
    expectedCloseDate: '2026-01-30',
    probabilityPct: 100,
    source: 'Existing Customer',
    ownerName: 'Alex Rivera',
    nextStep: 'Project kick-off completed',
    lastActivityAt: '2026-01-30',
    tags: ['Won Deal', 'Recurring'],
    createdAt: '2026-01-02',
    updatedAt: '2026-01-30',
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: 'demo-task-1',
    workspaceId: DEMO_WORKSPACE_ID,
    dealId: 'demo-deal-3',
    contactId: 'demo-cont-3',
    dealTitle: 'Horizon Digital Media',
    contactName: 'Elena Rostova',
    title: 'Follow up on proposal review with Elena Rostova',
    dueDate: new Date().toISOString().split('T')[0], // Due Today
    priority: 'urgent',
    status: 'pending',
    assignedToName: 'Alex Rivera',
    createdAt: '2026-02-10',
  },
  {
    id: 'demo-task-2',
    workspaceId: DEMO_WORKSPACE_ID,
    dealId: 'demo-deal-1',
    contactId: 'demo-cont-1',
    dealTitle: 'Nexus Dynamics',
    contactName: 'Sarah Chen',
    title: 'Send updated SOC2 compliance brief to Sarah Chen',
    dueDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().split('T')[0], // Overdue by 1 day
    priority: 'high',
    status: 'pending',
    assignedToName: 'Alex Rivera',
    createdAt: '2026-02-08',
  },
  {
    id: 'demo-task-3',
    workspaceId: DEMO_WORKSPACE_ID,
    dealId: 'demo-deal-4',
    contactId: 'demo-cont-4',
    dealTitle: 'Cobalt BioTech',
    contactName: 'David Sterling',
    title: 'Confirm procurement purchase order receipt with David Sterling',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'normal',
    status: 'pending',
    assignedToName: 'Alex Rivera',
    createdAt: '2026-02-12',
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'demo-inv-1',
    workspaceId: DEMO_WORKSPACE_ID,
    invoiceNumber: 'INV-2026-001',
    customerId: 'demo-comp-1',
    customerName: 'Nexus Dynamics',
    status: 'overdue',
    issueDate: '2026-01-05',
    dueDate: '2026-02-05',
    amount: 22500,
    currency: 'USD',
    amountPaid: 0,
    balanceDue: 22500,
    notes: 'Q1 Onboarding & Platform Architecture Phase 1',
    lastReminderSentAt: '2026-02-08',
    createdAt: '2026-01-05',
    updatedAt: '2026-02-08',
  },
  {
    id: 'demo-inv-2',
    workspaceId: DEMO_WORKSPACE_ID,
    invoiceNumber: 'INV-2026-002',
    customerId: 'demo-comp-4',
    customerName: 'Cobalt BioTech',
    status: 'due_soon',
    issueDate: '2026-01-20',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 30000,
    currency: 'USD',
    amountPaid: 15000,
    balanceDue: 15000,
    notes: 'Pilot implementation 50% milestone payment',
    createdAt: '2026-01-20',
    updatedAt: '2026-01-20',
  },
  {
    id: 'demo-inv-3',
    workspaceId: DEMO_WORKSPACE_ID,
    invoiceNumber: 'INV-2026-003',
    customerId: 'demo-comp-2',
    customerName: 'Vanguard Logistics',
    status: 'paid',
    issueDate: '2026-01-10',
    dueDate: '2026-01-25',
    amount: 18000,
    currency: 'USD',
    amountPaid: 18000,
    balanceDue: 0,
    notes: 'Integration Discovery Workshop (Paid in Full)',
    createdAt: '2026-01-10',
    updatedAt: '2026-01-24',
  },
];

export const DEMO_TRANSACTIONS: NormalizedRecord[] = [
  {
    id: 'demo-tx-1',
    date: '2026-01-10',
    revenue: 18000,
    expense: 0,
    profit: 18000,
    customer: 'Vanguard Logistics',
    category: 'Consulting & Implementation',
    currency: 'USD',
    paymentMethod: 'Wire Transfer',
  },
  {
    id: 'demo-tx-2',
    date: '2026-01-15',
    revenue: 0,
    expense: 3400,
    profit: -3400,
    category: 'Software & Cloud Infrastructure',
    product: 'AWS & Database Hosting',
    currency: 'USD',
    paymentMethod: 'Corporate Card',
  },
  {
    id: 'demo-tx-3',
    date: '2026-01-20',
    revenue: 15000,
    expense: 0,
    profit: 15000,
    customer: 'Cobalt BioTech',
    category: 'Software License',
    currency: 'USD',
    paymentMethod: 'ACH Transfer',
  },
  {
    id: 'demo-tx-4',
    date: '2026-01-28',
    revenue: 0,
    expense: 4200,
    profit: -4200,
    category: 'Contractor Services & Delivery',
    currency: 'USD',
    paymentMethod: 'Direct Transfer',
  },
];
